<?php

    function putHazifeladat($ADAT) {

	echo '<fieldset class="adatok"><legend>'._ALAPADATOK.'</legend>'."\n";

	    echo '<span class="oraAdat" data-oraid="'.$ADAT['oraAdat']['oraId'].'">';
	    echo ($ADAT['oraAdat']['dt']).' ('.$ADAT['oraAdat']['dt'].'), '.$ADAT['oraAdat']['ora'].'. '._ORA;
	    echo '</span>';
	    echo ' – <span class="tankorNev tankorAdat" data-tankorid="'.$ADAT['oraAdat']['tankorId'].'">'.$ADAT['oraAdat']['tankorNev'].'</span>';
	    echo ' – <span class="tanarNev" data-tanarid="'.$ADAT['oraAdat']['ki'].'">'.$ADAT['oraAdat']['kiCn'].'</span>';
	    // echo '<p>'.$ADAT['oraAdat']['leiras'].'</p>';

	echo '</fieldset>'."\n";

	if (__DIAK===true) { ////////////////////////////////////////////////////////////////////////////////////////////////

	    if ($ADAT['hazifeladatDiak']['hazifeladatDiakStatus']=='kész') $_class = "kesz";

	    echo '<fieldset class="adatok"><legend>'.ucfirst(_TANANYAG).'</legend>'."\n";
		if ($ADAT['oraAdat']['leiras']=='') 
		    { echo '<p style="color:#aaa;">még nincs kitöltve</p>'; }
		else 
		    { echo '<p>'.$ADAT['oraAdat']['leiras'].'</p>'; }
	    echo '</fieldset>'."\n";
	    echo '<fieldset class="adatok '.$_class.'"><legend>'._HAZIFELADAT.'</legend>'."\n";
		if ($ADAT['hazifeladatAdat']['hazifeladatLeiras']=='') 
		    { echo '<p style="color:#aaa;">még nincs kitöltve</p>'; }
		else 
		    { echo ($ADAT['hazifeladatAdat']['hazifeladatLeiras']); }
	    echo '</fieldset>'."\n";


	    if ($ADAT['hazifeladatDiak']['hazifeladatId']>0) {

		echo '<fieldset class="adatok '.$_class.'"><legend>'._HAZIFELTOLTES.'</legend>'."\n";
		echo formBegin(array('enctype'=>'multipart/form-data'));

		if (FILE_UPLOAD_ENABLED===false || $ADAT['hazifeladatAdat']['hazifeladatFeltoltesEngedely'] == 0 || $ADAT['hazifeladatDiak']['tanarLattamDt']!='' || $ADAT['hazifeladatDiak']['hazifeladatDiakStatus']=='kész') {
		    if (FILE_UPLOAD_ENABLED===false) $mert = ', mert a feltöltés le van tiltva';
		    elseif ($ADAT['hazifeladatAdat']['hazifeladatFeltoltesEngedely']==0) $mert = ', mert a tanár nem kért ide csatolt házi feladatot';
		    elseif ($ADAT['hazifeladatDiak']['tanarLattamDt']!='') $mert = ', mert már láttamozta a tanár';
		    elseif ($ADAT['hazifeladatDiak']['hazifeladatDiakStatus']=='kész') $mert = ', mert már késznek jelölted a feladatot';
		    echo '<p style="color:#888">nem tudsz új filet feltölteni'.$mert.'</p>';
		} else {
		    echo '<div style="width:100%; margin:auto; background-color: #eee; text-align:center; padding:20px 0px 20px 0px; border-radius: 2px;">';
		    echo '<input type="hidden" name="action" value="hazifeladatFeltoltes">';
		    echo '<input type="file" name="upfile"  /> (maximum méret: '.human_filesize(file_upload_max_size()).')';
		    if ($ADAT['hazifeladatDiak']['hazifeladatDiakFilename']!='') {
			$submitSzoveg = 'a korábbi feltöltés cseréje';
		    } else {
			$submitSzoveg = 'feltöltés';
		    }
		    echo '    <input type="submit" value="'.$submitSzoveg.'">';
		    echo '</div>';
		}

		if ($ADAT['hazifeladatDiak']['hazifeladatDiakFilename']!='') {
		    $ADAT['dir'] = 'naplo/haladasi/hazifeladat';
		    $ADAT['file'] = $ADAT['hazifeladatDiak']['hazifeladatDiakFilename'];
		    $href = href('index.php?page=session&f=download&dir='.$ADAT['dir'].'&file='.$ADAT['file'].'&download=true');
		    echo '<h3>Feltöltve:</h3>';
		    echo '<ul><li>';
		    echo '<a href="'.$href.'" target="_blank">'.htmlspecialchars($ADAT['hazifeladatDiak']['hazifeladatDiakOrigFilename']).'</a> <span class="icon-paper-clip"></span>';
		    if ($ADAT['hazifeladatDiak']['tanarLattamDt']!='') {
			echo ' <span class="icon-ok-sign" style="color: lightgreen"></span> '.$ADAT['hazifeladatDiak']['tanarLattamDt'];
		    }
		    echo '</li></ul>';
		}

		echo formEnd();
		echo '</fieldset>';

		formBegin(array('class'=>'hazifeladat'));
		if ($ADAT['hazifeladatId']>0) {
		    echo '<div style="text-align:center; margin-bottom: 140px;">';		
		    echo '<input type="hidden" name="action" value="hazifeladatKesz">';
		    if ($ADAT['hazifeladatDiak']['hazifeladatDiakStatus']=='kész') {
			echo '<button type="submit" class="btnHfStatusz kesz"><span class="icon-ok-sign"></span> kész</button>';
		    } else {
			echo '<button type="submit" class="btnHfStatusz"><span class="icon-ok-sign"></span> késznek jelölöm</button>';
		    }
		    echo '</div>';
		}
		echo formEnd();


	    }

	} else { ////////////////////////////////////////////////////////////////////////////////////
	    echo '<script src="//cdn.ckeditor.com/4.14.0/standard/ckeditor.js"></script>';
	    if ($skin != 'ajax') formBegin(array('class'=>'hazifeladat'));
	    echo '<input type="hidden" name="action" value="hazifeladatBeiras"/>';
	    echo '<input type="hidden" name="oraId" value="'.$ADAT['oraAdat']['oraId'].'"/>';
	    echo '<input type="hidden" name="hazifeladatId" value="'.$ADAT['hazifeladatId'].'"/>';

	    echo '<fieldset class="adatok"><legend>'.ucfirst(_TANANYAG).'</legend>'."\n";
		if ($ADAT['oraAdat']['oraId']>0 && strtotime(date('Y-m-d'))>=strtotime($ADAT['oraAdat']['dt'])) {
		    echo '<input type="text" name="oraLeiras" value="'.$ADAT['oraAdat']['leiras'].'" style="width:70%">';
		    echo '<input type="submit">';
		} else {
		    echo '<p>'.$ADAT['oraAdat']['leiras'].'</p>';
		}
	    echo '</fieldset>'."\n";

	    echo '<fieldset class="adatok"><legend>'._HAZIFELADAT.'</legend>'."\n";
	    echo '<textarea name="hazifeladatLeiras" class="wysiwyg" rows="10" cols="80" style="width:100%">';
		echo htmlspecialchars($ADAT['hazifeladatAdat']['hazifeladatLeiras']);
	    echo '</textarea>';
	    echo "
                <script>
                        CKEDITOR.replace( 'hazifeladatLeiras', {
			    disableNativeSpellChecker: true,
    language: 'hu',

    toolbarGroups: [
	{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
	{ name: 'paragraph',   groups: [ 'list', 'indent' ] },
	{ name: 'links' },
//	{ name: 'document',	   groups: [ 'mode', 'document', 'doctools' ] },
	{ name: 'clipboard',   groups: [ 'undo', 'redo' ] },
//	{ name: 'editing',     groups: [ 'find', 'selection', 'spellchecker' ] },
//	{ name: 'forms' },
//	{ name: 'insert' },
//	{ name: 'styles' },
//	{ name: 'colors' },
//	{ name: 'others' },
	{ name: 'insert', groups: [ 'Image', 'Table', 'HorizontalRule' ] },
	{ name: 'tools' },
//	{ name: 'about' }
	],
      removeButtons: 'Cut,Copy,Paste,PasteText,PasteFromWord,Anchor,Underline,Strike,SpecialChar,HorizontalRule'
			});
                </script>";

	    $_CHK = ($ADAT['hazifeladatAdat']['hazifeladatFeltoltesEngedely']==1) ? 'checked="checked"':'';
	    $_cls = ($ADAT['hazifeladatAdat']['hazifeladatFeltoltesEngedely']==1) ? 'class="engedelyezve"':'';
	    echo '<div id="hazifeladatFeltoltesEngedely" '.$_cls.'>';
		echo '<input type="checkbox" name="hazifeladatFeltoltesEngedely" id="hazifeladatFeltoltesEngedelyChk" value="1" '.$_CHK.'/>';
		echo '<label for="hazifeladatFeltoltesEngedelyChk">Diák/Szülő házi feladat csatolás engedélyezve</label>';
	    echo '</div>';
	    echo '<div style="width:100%; margin:auto; text-align:center;">';
    		echo '<input type="submit" class="btnSubmit">';
	    echo '</div>';
	    echo '</fieldset>'."\n";
	    if ($skin != 'ajax') formEnd();

	    if (count($ADAT['hazifeladatDiak'])>0) {
		echo '<fieldset class="adatok">';
		echo '<legend>Visszajelzések</legend>';
		putHazifeladatDiak($ADAT);
		echo '</fieldset>';
	    }
	}
    }

    function putHazifeladatDiak($ADAT) {

	if (count($ADAT['hazifeladatDiak'])==0) return false;

	echo formBegin();
	echo '<input type="hidden" name="action" value="lattam" />';
	echo '<input type="hidden" name="hazifeladatId" value="'.$ADAT['hazifeladatId'].'" />';
	echo '<table class="hazifeladatDiak" cellpadding="1" cellspacing="1">';
	echo '<thead>';
	    echo '<tr><th>diák</th><th>látta</th><th colspan="2">státusz</th><th colspan="1">csatolmány</th><th>láttam</th></tr>';
	echo '</thead>';
	for ($i=0; $i<count($ADAT['hazifeladatDiak']); $i++) {
	    $D = $ADAT['hazifeladatDiak'][$i];
	    echo '<tr>';   
	    echo '<td class="diakNev diakAdat" data-diakid="'.$D['diakId'].'">'.$D['diakNev'].'</td>';
	    echo '<td>'.$D['diakLattamDt'].'</td>';
	    echo '<td>'.$D['hazifeladatDiakStatus'].'</td>';
	    echo '<td>'.$D['hazifeladatDiakMegjegyzes'].'</td>';

	    $ADAT['dir'] = 'naplo/haladasi/hazifeladat';
	    $ADAT['file'] = $D['hazifeladatDiakFilename'];
	    $href = href('index.php?page=session&f=download&dir='.$ADAT['dir'].'&file='.$ADAT['file'].'&download=true');
	    echo '<td>';
		if ($D['hazifeladatDiakOrigFilename']!='') {
		    echo '<a href="'.$href.'" target="_blank">'.htmlspecialchars($D['hazifeladatDiakOrigFilename']).'</a> <span class="icon-paper-clip"></span>';
		}
	    echo '</td>';
	    echo '<td style="text-align: center">';
//		if ($ADAT['hazifeladatDiak']['hazifeladatDiakStatus']=='kész') {
		if (__TANAR===true) {
		    if ($D['tanarLattamDt']=='') {
			echo '<button type="submit" name="lattam[]" value="'.$D['diakId'].'" class="btnLattamStatusz"><span class="icon-ok-sign"></span> láttam!</button>';
		    } else {
			echo '<button type="submit" class="btnLattamStatusz lattam"><span class="icon-ok-sign"></span> láttam.</button>';
		    }
		} else {
		    if ($D['tanarLattamDt']!='') {echo '<span class="icon-ok-sign" style="color:lightblue"></span>';}		    
		}
//		}
	    echo '</td>';
	    echo '</tr>';
	}
	echo '</table>';
	echo formEnd();
    }

?>
