<?php

    function putHetesForm($ADAT) {

	formBegin(array('class'=>'hetes'));
	    echo '<input type="hidden" name="igDt" value="'._SHOW_DAYS_TO.'" />'."\n";
	    echo '<input type="hidden" name="osztalyId" value="'.$ADAT['osztalyId'].'" />'."\n";
	    echo '<input type="hidden" name="dt" value="'._SHOW_DAYS_FROM.'" />'."\n";
	    echo '<input type="hidden" name="action" value="hetesFelvetel" />'."\n";

	    echo '<table align="center" class="hetes" cellpadding="1" cellspacing="1" >';
	    if (is_array($ADAT['hetesek'])) foreach (($ADAT['hetesek']) as $osztalyId=>$D) {
		echo '<tr><th colspan="3">'.$ADAT['osztalyok'][$osztalyId]['osztalyJel'].' '.$ADAT['osztalyok'][$osztalyId]['osztalyfonokNev'].'</th></tr>';
		for ($k = 0; $k < count($D); $k++) {
/*
		$SEL = array($D[$k]['diakId'] => ' selected="selected" ');
		echo '<select name="hetes'.$k.'">'."\n";
		    echo '<option value=""> - </option>'."\n";
		    for ($i = 0; $i < count($ADAT['diakok']); $i++) {
			echo '<option value="'.$ADAT['diakok'][$i]['diakId'].'"'.$SEL[ $ADAT['diakok'][$i]['diakId'] ].'>'.$ADAT['diakok'][$i]['diakNev'].'</option>'."\n";
		    }
		echo '</select>'."\n";
*/
		    echo '<tr>';
		    echo '<td>'.str_replace('-','.',$D[$k]['dt']).'.</td>';
		    echo '<td>'.$D[$k]['sorszam'].'</td>';
		    echo '<td>'.$ADAT['diakok'][$D[$k]['diakId']]['diakNev'].'</td>';
		    echo '</tr>';
	        }
	    }
	    echo '</table>';
//	    echo '<input type="submit" value="'._OK.'" />'."\n";
	formEnd();

    }

?>
