<?php

    function putHirek($ADAT) {

	if (count($ADAT['hirek']['szovegek'])==0) {

	    if (_POLICY=='public') {
		echo '<div style="width:100%;  color:#eee; text-align:center;margin-top:40px;margin-bottom:40px;"><span style="font-size:120px;" class="icon-eye-close"></span><br/>Nincs aktuális hír</div>';
	    }

	} else {
	  for ($i=0; $i<count($ADAT['hirek']['szovegek']); $i++) {

	    $D = $ADAT['hirek']['szovegek'][$i];
	    $_class = ($D['class']==6 && _POLICY!='public') ? 'asPrivate':'';
	    list ($a,$b) = explode('<!-- more -->',$D['txt']);

	    echo '<div class="egyHir '.$_class.'">';
	    echo '<div class="hirCim">';
		if ($D['class']==6) {
		    echo '<span title="Védett hír" class="icon-lock-alt" style="padding-right:4px;"></span>';
		}
		echo '<a href="'.href('index.php?page=portal&sub=portal&f=hir&hirId='.$D['id']).'">'.$D['cim'].'</a>';

	    echo '</div>';
	    echo '<div class="hir">';
		echo $a;
		if ($b!="") echo ' <a href="'.href('index.php?page=portal&sub=portal&f=hir&hirId='.$D['id']).'">Tovább...</a>';
	    echo '</div>';
	    for ($j=0; $j<count($ADAT['hirek']['linkek'][$D['id']]); $j++) {
		echo '<a href="'.$ADAT['hirek']['linkek'][$D['id']][$j]['uri'].'">';
		echo $ADAT['hirek']['linkek'][$D['id']][$j]['szoveg'];
		echo '</a>';
	    }

	    if ($D['csoport']!='') {
		$CSOPORT = explode(',',$D['csoport']);
		echo '<div style="margin-top:10px">';
		for ($j=0; $j<count($CSOPORT); $j++) echo '<span class="tag">'.$CSOPORT[$j].'</span>';
		echo '</div>';
	    }
	    echo '<div style="display:none; font-size:10px; padding:2px; text-align:right; color:#aaa">'.($ADAT['hirek']['szovegek'][0]['kdt']).'</div>';
	    echo '<hr style="clear:both; height:0px; margin-top:2em; margin-bottom:2em; width:80%; background-color: #777777; border-style: solid; border-color: #eeeeee; border-width: 0px 0px 1px 0px;" />';
	    echo '</div>';
	  }
	}
    }

?>
