<?php

    function putTTFimport($ADAT) {
	/*
	formBegin();
	    echo '<input type="hidden" name="action" value="upload" />';
	    echo '<input type="file">';
	    echo '<input type="submit">';
	formEnd();

        formBegin(array('enctype'=>"multipart/form-data",'class'=>'diak'));
            echo '<fieldset><legend>'.'</legend>'."\n";
            echo '<input type="hidden" name="diakId" value="'.$diakId.'" />';
            echo '<input type="hidden" name="action" value="upload" />';
            echo '<input type="file" name="upfile" />';
            echo '<input type="submit" class="diakSubmit" value="ok" />';
            echo '</fieldset>';
        formEnd();
	*/

	echo '<style type="text/css">
	    
	    table.ttf { background-color: #eee;}
	    table.ttf thead tr th { background-color: #ddd;border-bottom: solid 1px #888; padding: 4px;}
	    table.ttf tr.tankorHozzarendel2.exact td { background-color: cornflowerblue}
	    table.ttf tr.tankorHozzarendel td { background-color: yellow}
	    table.ttf tr.tankorHozzarendel2 td { background-color: orange}
	    table.ttf tr.tankorHozzarendel3 td { background-color: #f44336; }

	    table.ttf tr.createTankor td { background-color: magenta;}
	    table.ttf tr.done td { background-color: lightgreen;}
	    table.ttf tr td {padding:4px;}

	    table.ttf tr td div.tankorLista span:hover { color: white; }
	</style>';

	// FILTEREZÉS


	
	formBegin();

	echo '<input type="submit" />';
	echo '<input type="hidden" name="action" value="do" />';
	echo '<input type="hidden" name="selectedTanarId" value="'.$ADAT['selectedTanarId'].'" />';
	echo '<input type="hidden" name="selectedTargyId" value="'.$ADAT['selectedTargyId'].'" />';
	echo '<table class="ttf" cellspacing="1">';

	echo '<thead>';
/*	echo '<tr>';
	    echo '<th>';
		echo 'Csoportnév';
	    echo '</th>';
	    echo '<th>';
		echo "Névsor";
	    echo '</th>';
	    echo '<th>';
	    echo '</th>';
	echo '</tr>';
*/	echo '<tr>';
	    echo '<th colspan="6">';
		foreach ( array('tankorHozzarendel','tankorHozzarendel2','tankorHozzarendel3','done','createTankor') as $k => $v) {
		    echo '<input type="checkbox" name="'.$v.'" value="'.$v.'" checked="checked" />';
		}
		echo '<button type="button" class="nevsorSzinkron_btn">minden kész névsort szinkronizálásra jelöl</button>';
	    echo '</th>';
	echo '</tr>';
	echo '</thead>';

	for ($i=0; $i<count($ADAT['records']); $i++) {
	    $D = $ADAT['records'][$i];
	    for ($j=0; $j<count($ADAT['szemeszterek']); $j++) {
		$_oraszamok[] = 'SZ'.$ADAT['szemeszterek'][$j].'='.$D['oraszam'];
	    }
	    $_O = (implode('&',$_oraszamok));
	    $_osztalyok = implode(',',$ADAT['csoportAdat'][$D['csoportNev']]['osztalyok']);

	    if (in_array($D['action'],array('tankorHozzarendel','tankorHozzarendel2','tankorHozzarendel3')) && count($D['displayTankor'])==1) {
		$_class = 'exact';
	    } else {
		$_class = '';
	    }
	    echo '<tr class="'.$D['action'].' '.$_class.'">';
		echo '<td class="tankorCsoportAdat" data-tankorcsoportid="'.$D['csoportId'].'">'.$D['csoportNev'].'</td>';
		echo '<td style="font-size:10px">';

			echo '<div>';
			for ($j=0;$j<count($ADAT['csoportAdat'][$D['csoportNev']]['diakNevsor']); $j++) {
			    echo $ADAT['csoportAdat'][$D['csoportNev']]['diakNevsor'][$j];
			    echo '<br/>';
			}
			echo '</div>';

		echo '</td>';
		echo '<td>'.$D[2].' '.'('.$D['targyId'].')</td>';
		echo '<td>'.$D[3].' '.'</td>';
		echo '<td class="tanarNev" data-tanarId="'.$D['tanarId'].'">'.$D[4].' ('.$D['tanarId'].')</td>';
		echo '<td>';

		    if (in_array($D['action'],array('tankorHozzarendel','tankorHozzarendel2','tankorHozzarendel3'))) {


			echo '<select name="tankor2csoport[]">';
			echo '<option>--'.$D['action'].'--</option>';
			for ($j=0; $j<count($D['displayTankor']); $j++) {
			    $_SEL = (count($D['displayTankor'])==1 && $D['action']=='tankorHozzarendel') ? ' selected="selected" ': '';
			    echo '<option value="'.$D['csoportId'].':####:'.$D['tanarId'].':####:'.$D['displayTankor'][$j]['tankorId'].':####:'.$D['oraszam'].'"    '.$_SEL.'>'.$D['displayTankor'][$j]['tankorNev'].'</option>';
			}
			echo '</select>';
			echo '<div class="tankorLista">';
			for ($j=0; $j<count($D['displayTankor']); $j++) {
			    $_tankorId = $D['displayTankor'][$j]['tankorId'];
			    $_diffCount = count(array_diff(
				$ADAT['csoportAdat'][$D['csoportNev']]['diakIds'],
				$ADAT['tankorDiak'][$_tankorId]
			    ));

			    echo '<br/><span class="tankorAdat" data-tankorid="'.$D['displayTankor'][$j]['tankorId'].'">'.$D['displayTankor'][$j]['tankorNev'].'</span>';
			    echo '('.$_tankorId.') tag: '.count($ADAT['tankorDiak'][$_tankorId]);

			    echo " -- diff:" .$_diffCount;
			    if ($_diffCount == 0) echo ' *******';
			}
			echo '</div>';
			// ha ezt összehasonlítom a mayorban rögzített névsorral, akkor eldönhető lehet, hogy melyik a jó választás!
			echo ' Új tankör:';
			echo '<input type="checkbox" name="ujTankor[]" value="'.$D['csoportId'].':####:'.$D['tanarId'].':####:'.$_osztalyok.':####:'.$D['targyId'].'.'.':####:'.$_O.':####:'.$D[1].'" />';
		    } elseif ($D['action'] == 'createTankor') {
			echo 'Új tankör létrehozása: <input type="text" name="ujTankor[]" value="'.$D['csoportId'].':####:'.$D['tanarId'].':####:'.$_osztalyok.':####:'.$D['targyId'].'.'.':####:'.$_O.':####:'.$D[1].'" />';
		    } else {
			echo '<div class="tankor tankorAdat tankorNev" data-tankorid="'.$D['tankorId'].'">'.$D['tankorId'].'</div>';

			echo '<input type="checkbox" name="nevsorSzinkronFelulir[]" value="'.$D['csoportId'].':####:'.$D['tankorId'].'" class="nevsorSzinkronizal" />névsor felülír import alapján';


			/*
			echo '<label for="tnf_'.$i.'_1"><span class="icon-record"></span>';
			echo ' nem frissít</label>';
			echo '<input type="radio" name="tankorNevsorFrissit[]" value="" id="tnf_'.$i.'_1" />';
			echo '<br/>';
			echo '<label for="tnf_'.$i.'_2"><span class="icon-random"></span>';
			echo ' importál (kibővít)</label>';
			echo '<input type="radio" name="tankorNevsorFrissit[]" value="'.$D['csoportId'].':####:'.$D['tankorId'].'"  id="tnf_'.$i.'_2" />';
			echo '<br/>';
			echo '<label for="tnf_'.$i.'_3"><span class="icon-download"></span>';
			echo ' töröl és importál</label>';
			echo '<input type="radio" name="tankorNevsorFrissit[]" value="'.$D['csoportId'].':####:'.$D['tankorId'].'"  id="tnf_'.$i.'_3" />';
			*/
		    }

		echo '</td>';
	    echo '</tr>';
	}
	echo '</table>';
	echo '<input type="submit" />';

	formEnd();

    }


?>