DELETE FROM `feladatTipus`;
INSERT INTO feladatTipus (feladatTipusId,feladatTipusLeiras,beszamithatoMaxOra) VALUES (1,'felkészülés foglalkozásra, tanórára',10);
INSERT INTO feladatTipus (feladatTipusId,feladatTipusLeiras,beszamithatoMaxOra) VALUES (2,'diákok teljesítményének értékelése',10);
INSERT INTO feladatTipus (feladatTipusId,feladatTipusLeiras,beszamithatoMaxOra) VALUES (31,'sportélet és szabadidő szervezése',10);
INSERT INTO feladatTipus (feladatTipusId,feladatTipusLeiras,beszamithatoMaxOra) VALUES (4,'diákönkormányzat segítése',10);
INSERT INTO feladatTipus (feladatTipusId,feladatTipusLeiras,beszamithatoMaxOra) VALUES (7,'gyermek- és ifjúságvédelmi feladat',10);
INSERT INTO feladatTipus (feladatTipusId,feladatTipusLeiras,beszamithatoMaxOra) VALUES (9,'adminisztráció, dokumentumkészítés',10);
INSERT INTO feladatTipus (feladatTipusId,feladatTipusLeiras,beszamithatoMaxOra) VALUES (11,'szülői értekezlet, fogadóóra (kapcsolattartás)',10);
INSERT INTO feladatTipus (feladatTipusId,feladatTipusLeiras,beszamithatoMaxOra) VALUES (13,'mentorálás',10);
INSERT INTO feladatTipus (feladatTipusId,feladatTipusLeiras,beszamithatoMaxOra) VALUES (14,'nevelőtestületi, munkaközösségi feladat',10);
INSERT INTO feladatTipus (feladatTipusId,feladatTipusLeiras,beszamithatoMaxOra) VALUES (16,'intézményfejlesztés, -karbantartás',10);
INSERT INTO feladatTipus (feladatTipusId,feladatTipusLeiras,beszamithatoMaxOra) VALUES (17,'környezeti nevelés',10);
INSERT INTO feladatTipus (feladatTipusId,feladatTipusLeiras,beszamithatoMaxOra) VALUES (20,'telephelyközi utazás',10);
INSERT INTO feladatTipus (feladatTipusId,feladatTipusLeiras,beszamithatoMaxOra) VALUES (22,'iskolai redezvény',10);
INSERT INTO feladatTipus (feladatTipusId,feladatTipusLeiras,beszamithatoMaxOra) VALUES (32,'versenyfelügyelet, versenyeztetés',10);
