<?php

    function putCreateAzonositoForm($osztalyId, $osztalyTagok, $tanev=__TANEV, $Tagok) {

	global $AUTH;

	formBegin(array('class'=>'azonosito'));

	echo '<input type="hidden" name="action" value="createAzonosito" />'."\n";
	echo '<input type="hidden" name="osztalyId" value="'.$osztalyId.'" />'."\n";
	echo '<input type="hidden" name="tanev" value="'.$tanev.'" />'."\n";

	echo '<table>';
	echo '<tr><th colspan="9">';
	    echo _JELSZO;
	    echo ' <input type="text" name="userPassword" value="" />'."\n";
	echo '</th></tr>'."\n";

        $CONTAINERS = $AUTH['parent'][ $AUTH['private']['backend'].'Containers'];                                                                                          
        if (isset($CONTAINERS) and is_array($CONTAINERS) and count($CONTAINERS) > 0) {                                                                                      
        echo '<tr><th colspan="4">';                                                                                                                                        
            echo _CONTAINER;                                                                                                                                                
            echo '<select name="container">';                                                                                                                               
            echo '<option value=""> - </option>'."\n";                                                                                                                      
            for ($i=0;$i<count($CONTAINERS);$i++) {                                                                                                                         
                echo '<option value="'.$CONTAINERS[$i].'">'.$CONTAINERS[$i].'</option>';                                                                                    
            }                                                                                                                                                               
            echo '</select>';                                                                                                                                               
        echo '</th></tr>'."\n";                                                                                                                                             
        }                                                                                                                                                                   

	echo '<tr>';
	    echo '<th>'._NEV.'</th>'."\n";

	    echo '<th>'._ANYANEV.'</th>'."\n";
	    echo '<th>'._ANYAAZONOSITO.'</th>'."\n";
	    echo '<th>'._ANYA_FELHASZNALO.'</th>'."\n";
	    echo '<th>'._ANYA_HASONLO_NEV.'</th>'."\n";

	    echo '<th>'._APANEV.'</th>'."\n";
	    echo '<th>'._APAAZONOSITO.'</th>'."\n";
	    echo '<th>'._APA_FELHASZNALO.'</th>'."\n";
	    echo '<th>'._APA_HASONLO_NEV.'</th>'."\n";

	echo '</tr>';
	for ($i = 0; $i < count($osztalyTagok); $i++) {
	    echo '<tr>';

	    echo '<th>';
		echo $osztalyTagok[$i]['diakNev'];
	    echo '</th>';
	    foreach (array('anya','apa') as $szulo) {
		if ($osztalyTagok[$i][$szulo]['szuloNev'] == '') {
		    echo '<td></td><td></td><td></td><td></td>';
		    continue;
		}
		echo '<td class="'.$szulo.'">';
		echo $osztalyTagok[$i][$szulo]['szuloNev'];

		echo '</td>';
		echo '<td class="'.$szulo.'">';
		if ($osztalyTagok[$i][$szulo]['statusz'] == 'elhunyt') { // elhunyt státuszú a szülő
		    echo '<span class="elhunyt">'._ELHUNYT.'</span>';
		} elseif (!isset($osztalyTagok[$i][$szulo.'Account'])) { // Ha nem találtunk létező $szulo.Account-ot
		    // ez kellene, hogy a szulő táblát módosítsuk...
		    echo '<input type="hidden" name="szuloId[]" value="'.$osztalyTagok[$i][$szulo.'Id'].'" />'."\n";
		    if ($osztalyTagok[$i][$szulo]['userAccount'] != '') { // de a szulő táblában be van írva
			echo '<input type="text" name="userAccount[]" value="'.$osztalyTagok[$i][$szulo]['userAccount'].'" />'."\n";
		    } else {
			echo '<input type="text" name="userAccount[]" value="'.$osztalyTagok[$i][$szulo.'GeneratedAccount'].'" />'."\n";
		    }
		    // generált jelszó
		    echo '<br />('.$osztalyTagok[$i][$szulo]['userPassword'].')';
		} else { 
		    if (false && $osztalyTagok[$i][$szulo]['email'] != '') { // nem megvalósított funkció...
			echo '<div style="float: right; display: inline-block; width: 50px; font-size: 1.5em; margin: -4px -16px 0 0; padding: 0;">';
			echo '&#009993;';
			echo '<input type="checkbox" name="mailto[]" title="'.$osztalyTagok[$i][$szulo]['email'].'" value="'.$osztalyTagok[$i][$szulo.'Id'].'" />';
			echo '</div>';
		    }
		    echo $osztalyTagok[$i][$szulo]['userAccount'];
		    // generált jelszó
		    echo '<br />('.$osztalyTagok[$i][$szulo]['userPassword'].')';
		}
		echo '</td>';		

		echo '<td class="'.$szulo.'">';
		if (isset($osztalyTagok[$i][$szulo.'Account'])) { // Ha találtunk létező $szulo.Account-ot
		    echo $osztalyTagok[$i][$szulo.'UserCn'];
		}
		echo '</td>';

		if (is_array($osztalyTagok[$i][$szulo.'Cns'])) {
		    $L = array();
		    for ($j = 0; $j < count($osztalyTagok[$i][$szulo.'Cns']); $j++) 
			$L[] = $osztalyTagok[$i][$szulo.'Cns'][$j].' ('.$osztalyTagok[$i][$szulo.'Accounts'][$j].')';
		    echo '<td class="azonosNev">'.implode(',<br />', $L).'</td>'."\n";
		} else {
		    echo '<td></td>'."\n";
		}
	    } // anya / apa
	    echo '</tr>'."\n";
	}
	echo '<tr>';
	    echo '<th colspan="9"><input type="submit" value="'._OK.'" /></th>';
	echo '</tr>';
	echo '</table>';

	formEnd();

    }

?>
