<?php

    function putResetPasswordForm($ADAT) {

	global $POLICIES, $AUTH;

	$toPolicy = $ADAT['policy'];
	$userAccount = $ADAT['userAccount'];

	echo '<h1 class="changePassword">'._RESET_PASSWORD.'</h1>'."\n";

	formBegin(array('action'=>location('index.php?page=password&f=resetPassword')));
	echo '<input type="hidden" name="action" value="resetPassword" />';
	echo '<input type="hidden" name="selector" value="'.$ADAT['selector'].'" />';
	echo '<input type="hidden" name="validator" value="'.$ADAT['validator'].'" />';

	echo '<table cellspacing="0" cellpadding="1" align="center" class="changePassword">'."\n";
	echo '<thead>'."\n";
	    echo '<tr>'."\n";
		echo '<th colspan="3">'."\n";
		echo constant('_'.strtoupper($toPolicy).'_PASSWORD');
		echo '<input type="hidden" name="toPolicy" value="'.$toPolicy.'" />'."\n";
    		echo '</th>'."\n";
	    echo '</tr>'."\n";
	echo '</thead>'."\n";
	echo '<tfoot>'."\n";
	    echo '<tr>'."\n";
    		echo '<th colspan="3">'."\n";
            	echo '<input type="submit" tabindex="3" name="button" value=" '. _OK .' "
			class="submit" />'."\n";
    		echo '</th>'."\n";
	    echo '</tr>'."\n";
	echo '</tfoot>'."\n";
	echo '<tbody>'."\n";
/*
    	    echo '<tr>'."\n";
        	echo '<td>'."\n";
            	    echo _USERNAME;
        	echo '</td>'."\n";
        	echo '<td>'."\n";
            	    echo '<input id="userAccount" type="text" readonly="readonly" tabindex="1" name="userAccount" value="'.$userCn.'" maxlength="32" />'."\n";
        	echo '</td>'."\n";
    	    echo '</tr>'."\n";
*/
    	    echo '<tr>'."\n";
        	echo '<td>'."\n";
            	    echo _USERNAME;
        	echo '</td>'."\n";
        	echo '<td>'."\n";
            	    echo '<input id="userAccount" type="text" readonly="readonly" tabindex="1" name="userAccount" value="'.$userAccount.'" maxlength="32" />'."\n";
        	echo '</td>'."\n";
    	    echo '</tr>'."\n";

	    echo '<tr>'."\n";
        	echo '<td>'."\n";
            	    echo _NEW_PASSWORD;
        	echo '</td>'."\n";
        	echo '<td>'."\n";
            	    echo '<input id="newPassword" type="password" accesskey="n" tabindex="3" name="newPassword" value="" maxlength="20" />'."\n";
        	echo '</td>'."\n";
    	    echo '</tr>'."\n";

	    echo '<tr>'."\n";
        	echo '<td>'."\n";
            	    echo _VERIFICATION;
        	echo '</td>'."\n";
        	echo '<td>'."\n";
            	    echo '<input id="verification" type="password" accesskey="v" tabindex="3" name="verification" value="" maxlength="20" />'."\n";
        	echo '</td>'."\n";
    	    echo '</tr>'."\n";

	echo '</tbody>'."\n";
	echo '</table>'."\n";

	formEnd();

    }

?>
