<?php

    function emailHead($includeCSS=array()) {

	$html = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><!--[if IE]><html xmlns="http://www.w3.org/1999/xhtml" class="ie"><![endif]--><!--[if !IE]><!--><html style="margin: 0;padding: 0;" xmlns="http://www.w3.org/1999/xhtml"><!--<![endif]-->
	    <head>
	    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	    <title></title>';

	// BASE CSS
	$html .= '<style type="text/css">
body {  margin: 0; padding: 0; font-family: Verdana, Arial, Helvetica, sans-serif; }
table { border-collapse: collapse; table-layout: fixed;}
* {  line-height: inherit;}
	</style>';

	// BEEPULO CSS-EK INLINE
	if (is_array($includeCSS) && count($includeCSS)>0) {
	    for ($i=0; $i<count($includeCSS); $i++) {
		$html .= '<style type="text/css">';
		$html .= file_get_contents($includeCSS[$i]); 
		$html .= '</style>';
	    }
	}

	$html .= '</head><body>';

	// DEFAULT EMAIL FEJLEC
	$html .= '<div class="emailFejlec">MaYoR Hírnök</div>';

	return $html;
    }

    function emailFoot() {

	$html = '<div style="text-align:center; padding:30px; font-size:x-small; color: #888;">MaYoR elektronikus napló (GPL)</div>
	</body></html>';
	return $html;

    }

?>