<?php

    function putLezarandoOsztalyValaszto($ADAT) {

	formBegin(array('class'=>'vegzos'));
	    echo '<input type="hidden" name="action" value="orarendLezaras" />'."\n";
	    echo '<input type="hidden" name="dt" value="'.$ADAT['dt'].'" />'."\n";

	    echo '<h1>'._LEZARANDO_OSZTALYOK_KIVALASZTASA.'</h1>';
    	    echo '<ul>'."\n";
	    for ($i = 0; $i < count($ADAT['osztalyok']); $i++) {

		if ($ADAT['osztalyok'][$i]['vegzoTanev'] == __TANEV) {
		    if (in_array($ADAT['osztalyok'][$i]['osztalyId'], $ADAT['lezarandoOsztaly'])) $CHK = ' checked="checked" ';
		    else $CHK = '';
		    echo '<li>';
		    echo '<input id="chk'.$i.'" type="checkbox" name="lezarandoOsztaly[]" value="'.$ADAT['osztalyok'][$i]['osztalyId'].'" '.$CHK.'/>'."\n";
		    echo '<label for="chk'.$i.'">';
		    echo $ADAT['osztalyok'][$i]['osztalyJel'];
		    echo '</label>';
		    echo '</li>'."\n";
		}

	    }
	    echo '</ul>'."\n";
	    echo '<input type="submit" value="'._OK.'" />'."\n";
	formEnd();


    }

?>
