<?php

function jatek2048() {
#  <link href="style/main.css" rel="stylesheet" type="text/css">

echo '
  <div class="container">
    <div class="heading">
      <h1 class="title">2048</h1>
      <div class="scores-container">
        <div class="score-container">0</div>
        <div class="best-container">0</div>
      </div>
    </div>

    <div class="above-game">
      <p class="game-intro">Join the numbers and get to the <strong>2048 tile!</strong></p>
      <a class="restart-button">New Game</a>
    </div>

    <div class="game-container">
      <div class="game-message">
        <p></p>
        <div class="lower">
	        <a class="keep-playing-button">Keep going</a>
          <a class="retry-button">Try again</a>
        </div>
      </div>

      <div class="grid-container">
        <div class="grid-row">
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
        </div>
        <div class="grid-row">
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
        </div>
        <div class="grid-row">
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
        </div>
        <div class="grid-row">
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
          <div class="grid-cell"></div>
        </div>
      </div>

      <div class="tile-container">

      </div>
    </div>

  </div>

  <script src="/skin/classic/module-jatek/js/bind_polyfill.js"></script>
  <script src="/skin/classic/module-jatek/js/classlist_polyfill.js"></script>
  <script src="/skin/classic/module-jatek/js/animframe_polyfill.js"></script>
  <script src="/skin/classic/module-jatek/js/keyboard_input_manager.js"></script>
  <script src="/skin/classic/module-jatek/js/html_actuator.js"></script>
  <script src="/skin/classic/module-jatek/js/grid.js"></script>
  <script src="/skin/classic/module-jatek/js/tile.js"></script>
  <script src="/skin/classic/module-jatek/js/local_storage_manager.js"></script>
  <script src="/skin/classic/module-jatek/js/game_manager.js"></script>
  <script src="/skin/classic/module-jatek/js/application.js"></script>
';
}

?>