<?php

function putFelveteliPontszamito() {

    $TARGYAK = array( 
	array('targyNev'=>'magyar nyelv és irodalom','allowHalf'=>true),
//	array('targyNev'=>'magyar nyelv','allowHalf'=>false),
	array('targyNev'=>'történelem'),
	array('targyNev'=>'matematika'),
	array('targyNev'=>'term.ism./fizika'),
	array('targyNev'=>'id. nyelv')
    );

    echo '<style type="text/css">
	h1,h2 { text-align: center }
	h3,p.info { padding: 5px 10px 0px 10px;}
	table.pontszamitoOsszegzo tr th { text-align: right; }
	table.pontszamito tr th { height: 2em; border-bottom: solid 1px #999;} 
	table.pontszamito tr td { border-bottom: solid 1px #aaa;} 
    </style>';

    echo '<h1>Városmajori Gimnázium Pontszámító</h1>';
    echo '<h2>2020/2021</h2>';

    echo '<form id="felviPontszamito"action="return false">';
	echo '<table align="center" class="pontszamito" style="margin: 2em auto 2em auto;" >';
	for ($evfolyam = 5; $evfolyam<=8; $evfolyam++) {
	    echo '<tr><th>'.$evfolyam.'. évfolyam</th>';
	    echo '<td>';
		echo '<button type="button" id="btn_'.$evfolyam.'_5" >mind jeles</button>';
		echo '<button type="button" id="btn_'.$evfolyam.'_4" >mind jó</button>';
	    echo '</td>';
	    foreach ($TARGYAK as $t => $t2) {
		echo '<td>';
		echo $t2['targyNev'];
		echo '</td>';
		echo '<td>';
		_putFPSelect('p_'.$evfolyam.'_'.$t, $t2['allowHalf']);
		echo '</td>';
	    }
	    echo '</tr>';
	}
	echo '</table>';
    echo '</form>';
    

    echo '<table class="pontszamitoOsszegzo" align="center" >';
    echo '<tr><th>Átlagod:</th><td><input type="text" id="targyAtlagok" readonly="readonly" /></td></tr>';
    echo '<tr><th>Hozott tanulmányi pontjaid:</th><td></td><td><input type="text" id="hozottPont"  readonly="readonly" />pont (max:20)</td></tr>';
    echo '<tr><th>Központi magyar dolgozatod eredménye:</th><td><input type="number" id="magyar" class="pontszamitoUpdate" min="0" max="50" />pont (max:50)</td><td><input type="number" value="0" id="magyarSzamitott" readonly="readonly" >pont (max: 50)</td></tr>';
    echo '<tr><th>Központi matematika dolgozatod eredménye:</th><td><input type="number" id="matek" class="pontszamitoUpdate"  min="0" max="50" />pont (max:50)</td><td><input type="number" value="0" id="matekSzamitott" readonly="readonly" >pont (max: 50)</td></tr>';
    echo '<tr><th>Számított majoros felvételi százalékosan:</th><td></td><td><input type="text" id="osszszazalek" readonly="readonly" />% (max:100)</td></tr>';
    echo '<tr><th>Számított majoros felvételi pontod:</th><td></td><td><input type="text" id="osszpont" readonly="readonly" />pont (max:120)</td></tr>';
    echo '</table>';

    echo '<h3>Tájékoztatás a pontszámításról</h3>';
    echo '<p class="info">50-50 pontot adhat a két felvételi dolgozat, és húsz pontot adhatnak az általános iskolai osztályzatok: 4,0-ra 0 pont, 5,0-ra 20 pont, egyébként arányosan (például 4,5-re 10 pont, 4,6-re 12 pont, 4,75-ra 15 pont és így tovább). Az elérhető maximális pontszám: 120 pont. Ehhez adódhat hozzá a szóbeli maximum 30 pont.</p>
    <p class="info">Hatodikosoknál a magyar nyelv és irodalom (egy tárgyként), a történelem, az idegen nyelv, a matematika és a természettudomány átlagát számoljuk (ha az utolsó hiányzik, a helyette tanított biológia, földrajz, fizika átlagait vesszük).</p>
<p class="info">Nyolcadikosoknál a magyar nyelv és irodalom (egy tárgyként), a történelem, az idegen nyelv, a matematika és a fizika (7-8.-os) átlagát számoljuk.</p>';

}

function _putFPSelect($name, $allowhalf=false) {

    echo '
    <select name="'.$name.'" id="'.$name.'" class="pontszamitoSelect pontszamitoUpdate">
	<option value="0">-</option>';
    for ($i=5; $i>1; $i--) {
	echo '<option value="'.$i.'">'.$i.'</option>';
	if ($allowhalf===true) echo '<option value="'.($i-1).'.5">'.($i-1).'.5</option>';

    }
    echo '</select>';

}
?>