<?php

    function putTargySzuro($ADAT) {

	formBegin(array('class'=>"szuro csoport"));
	echo '<input type="hidden" name="action" value="targySzures" />'."\n";
	echo '<input type="hidden" name="tanev" value="'.$ADAT['tanev'].'" />'."\n";
	if (is_array($ADAT['osztalySzuro']) && count($ADAT['osztalySzuro']) == 1) 
	    echo '<input type="hidden" name="osztalyId" value="'.$ADAT['osztalySzuro'][0].'" />'."\n";

	echo '<table>';

	echo '<tr>';
	    echo '<th>'._TARGY_SZURES.'</th>';
	echo '</tr>'."\n";

	echo '<tr>';
	    echo '<td>';
	    echo '<select name="targyId[]" multiple="multiple">';
	    for ($i = 0; $i < count($ADAT['targyak']); $i++) {
		if (in_array($ADAT['targyak'][$i]['targyId'], $ADAT['targySzuro']))
		    echo '<option value="'.$ADAT['targyak'][$i]['targyId'].'" selected="selected">'.$ADAT['targyak'][$i]['targyNev'].'</option>'."\n";
		else
		    echo '<option value="'.$ADAT['targyak'][$i]['targyId'].'">'.$ADAT['targyak'][$i]['targyNev'].'</option>'."\n";
	    }
	    echo '</select>'."\n";
	    echo '</td>';
	echo '</tr>'."\n";

	if (count($ADAT['osztalySzuro']) != 1) {
	    echo '<tr>';
		echo '<th>'._EVFOLYAM_SZURES.'</th>';
	    echo '</tr>'."\n";
	    echo '<tr>';
		echo '<td>';
		for ($i = 0; $i < count($ADAT['evfolyamJelek']); $i++) {
		    if (in_array($ADAT['evfolyamJelek'][$i], $ADAT['evfolyamJelSzuro'])) 
			echo '<input id="evf'.$i.'" type="checkbox" name="evfolyamJel[]" value="'.$ADAT['evfolyamJelek'][$i].'" checked="checked" /> ';
		    else 
			echo '<input id="evf'.$i.'" type="checkbox" name="evfolyamJel[]" value="'.$ADAT['evfolyamJelek'][$i].'" /> ';
		    echo '<label for="evf'.$i.'">'.$ADAT['evfolyamJelek'][$i].'.</label> ';
		    if ($i % 4 == 3) echo '<br />';
		}
		echo '</td>';
	    echo '</tr>'."\n";
	}

	echo '<tr>';
	    echo '<td>';
	    echo '<input type="submit" value="'._OK.'" />'."\n";
	    echo '</td>';
	echo '</tr>'."\n";

	echo '</table>'."\n";

	formEnd();

    }

    function putUjTankorBlokk($ADAT) {

	formBegin(array('class'=>'csoport'));
	echo '<input type="hidden" name="action" value="ujTankorBlokk" />'."\n";
	echo '<input type="hidden" name="tanev" value="'.$ADAT['tanev'].'" />'."\n";

	// Kiválasztott tárgyak és évfolyamok
	for ($i = 0; $i < count($ADAT['targySzuro']); $i++) echo '<input type="hidden" name="targyId[]" value="'.$ADAT['targySzuro'][$i].'" />'."\n";
	for ($i = 0; $i < count($ADAT['evfolyamJelSzuro']); $i++) echo '<input type="hidden" name="evfolyamJel[]" value="'.$ADAT['evfolyamJelSzuro'][$i].'" />'."\n";
	if (is_array($ADAT['osztalySzuro']) && count($ADAT['osztalySzuro']) == 1) 
	    echo '<input type="hidden" name="osztalyId" value="'.$ADAT['osztalySzuro'][0].'" />'."\n";

	echo '<table>';

	echo '<tr>';
	    echo '<th colspan="2">';
	    echo _UJ_TANKOR_BLOKK;
	    echo '</th>';
	echo '</tr>'."\n";

	echo '<tr>';
	    echo '<th>';
		echo _BLOKKNEV;
	    echo '</th>';
	    echo '<th>';
		echo _TANKOROK.'  ('.count($ADAT['tankorIdk']).')';
	    echo '</th>';
	echo '</tr>'."\n";

	echo '<tr>';
	    echo '<td>';
		echo '<input type="text" name="blokkNev" value="" /><br />';
		echo '<label for="exportOraszam">'._EXPORT_ORASZAM.':</label> ';
		echo '<input size="1" maxlength="4" type="text" name="exportOraszam" id="exportOraszam" value="" /><br />';
		echo '<input type="submit" value="'._OK.'" />';	    echo '</td>';
	    echo '<td>';
		echo '<select name="tankorId[]" multiple="multiple" size="10">';
		foreach ($ADAT['szurtTankorIdk'] as $key => $tankorId)
		if ($ADAT['tankorOraszam'][$tankorId] - $ADAT['tankorExportOraszam'][$tankorId] > 0)
		    echo '<option value="'.$tankorId.'">'.$ADAT['tankorAdat'][$tankorId]['tankorNev'].' ('.$tankorId.') - '
		    .number_format($ADAT['tankorOraszam'][$tankorId],1).' / '.number_format($ADAT['tankorExportOraszam'][$tankorId],1)
		    .' ['.$ADAT['tankorTanar'][$tankorId][0]['tanarNev'].' - ('.$ADAT['tankorTanar'][$tankorId][0]['tanarId'].')]'
		    .'</option>'."\n";
		echo '</select>'."\n";
	    echo '</td>';
	echo '</tr>'."\n";

	echo '</table>';    
	formEnd();

    }

    function putTankorBlokkok($ADAT) {

	$BLOKKOK = $ADAT['tankorBlokkok'];
	if (!is_array($BLOKKOK['blokkNevek'])) return false;
	echo '<table class="modosit">';

	echo '<tr>';
	    echo '<th>';
	    echo _TANKOR_BLOKK_MODOSITAS;
	    echo '</th>';
	echo '</tr>'."\n";

	foreach ($BLOKKOK['blokkNevek'] as $blokkId => $blokkNev) {
	    $BA = $BLOKKOK['idk'][$blokkId];

	    $kirakjuk = false;
	    // blokk szűrése a tankörök alapján (tehát tárgy és évfolyam alapján)
	    for ($i = 0; $i < count($BA); $i++) {
		if (in_array($BA[$i], $ADAT['szurtTankorIdk'])) {
		    $kirakjuk = true;
		    break;
    		}
	    }

	    if ($kirakjuk) {

		echo '<tr><td>';

		formBegin(array('class'=>'csoport'));
		echo '<input type="hidden" name="action" value="modTankorBlokk" />'."\n";
		echo '<input type="hidden" name="blokkId" value="'.$blokkId.'" />'."\n";
		echo '<input type="hidden" name="tanev" value="'.$ADAT['tanev'].'" />'."\n";

		// Kiválasztott tárgyak és évfolyamok
		for ($i = 0; $i < count($ADAT['targySzuro']); $i++) echo '<input type="hidden" name="targyId[]" value="'.$ADAT['targySzuro'][$i].'" />'."\n";
		for ($i = 0; $i < count($ADAT['evfolyamJelSzuro']); $i++) echo '<input type="hidden" name="evfolyamJel[]" value="'.$ADAT['evfolyamJelSzuro'][$i].'" />'."\n";
		if (is_array($ADAT['osztalySzuro']) && count($ADAT['osztalySzuro']) == 1) 
		    echo '<input type="hidden" name="osztalyId" value="'.$ADAT['osztalySzuro'][0].'" />'."\n";

		echo '<table>';

		echo '<tr>';
		    echo '<th>';
			echo _BLOKKNEV. ' ('.$blokkId.')';
		    echo '</th>';
		    echo '<th>';
			echo _TANKOROK. ' (' . count($BA).')';
		    echo '</th>';
		echo '</tr>'."\n";
		echo '<tr>';
		    echo '<td>';
			echo '<input type="text" name="blokkNev" value="'.htmlspecialchars($blokkNev, ENT_QUOTES, "UTF-8").'" /><br />';
			echo '<label for="exportOraszam'.$blokkId.'">'._EXPORT_ORASZAM.':</label> ';
			echo '<input size="1" maxlength="4" type="text" name="exportOraszam" id="exportOraszam'.$blokkId.'" value="'.number_format($BLOKKOK['exportOraszam'][$blokkId], 1, '.', ' ').'" /><br />';
			echo '<input type="submit" value="'._OK.'" />';
			echo '<input type="submit" name="del" value="'._DEL.'" />';
		    echo '</td>';
		    echo '<td>';
			echo '<select name="tankorIds[]" multiple="multiple" size="5">';
			foreach ($BA as $key => $tankorId)
			    echo '<option value="'.$tankorId.'" selected="selected">'
				    .$ADAT['tankorAdat'][$tankorId]['tankorNev'].' ('.$tankorId.') - '
				    .number_format($ADAT['tankorOraszam'][$tankorId],1).' / '.number_format($ADAT['tankorExportOraszam'][$tankorId],1)
				    .' ['.$ADAT['tankorTanar'][$tankorId][0]['tanarNev'].' - ('.$ADAT['tankorTanar'][$tankorId][0]['tanarId'].')]'
				    .'</option>'."\n";
			foreach ($ADAT['tankorAdat'] as $tankorId => $tankorAdat)
			    if (
				!in_array($tankorId,$BA)
				&& $ADAT['tankorOraszam'][$tankorId] - $ADAT['tankorExportOraszam'][$tankorId] > 0
			    ) echo '<option value="'.$tankorId.'" >'.$tankorAdat['tankorNev'].' ('.$tankorId.') - '
			    .number_format($ADAT['tankorOraszam'][$tankorId],2).' / '.intval($ADAT['tankorExportOraszam'][$tankorId])
			    .' ['.$ADAT['tankorTanar'][$tankorId][0]['tanarNev'].' - ('.$ADAT['tankorTanar'][$tankorId][0]['tanarId'].')]'
			    .'</option>'."\n";
			echo '</select>'."\n";
		    echo '</td>';
		echo '</tr>'."\n";

		echo '</table>';    
		formEnd();

		echo '</td></tr>'."\n";
	    } // if
	} // foreach

	echo '</table>'."\n";

    }

?>
