<?php
/*
    module:	naplo

    todo: függvény paraméterezések tisztítása (2010)

    függőségek:

    function putHaladasiBejegyzesek($data, $tankorId, $osztalyId, $tanarId, $title, $diakId, $order, $ADAT)
	|- function putNap($dt, $dNap, $napInfo, $doga, $napInfo2)
	    |-function putHaladasiDolgozat
	    |-function putOra($dOra)
	|- function putTankorNap($dt, $dNap, $doga, $order)
	    |-function putHaladasiDolgozat($dt,$doga)
	    |-function putTankorOra($dOra)
    function putHetesForm($ADAT)

*/
##
# Haladási naplo megjelenítése
##

    function putHaladasiBejegyzesek($ADAT) {

	global $_TANEV;

	// kompatibilitás miatt -- átnevezhetők
	$title = $ADAT['title'];
	$data  = $ADAT['haladasi'];
	$order = $ADAT['order'];
	//..
	$tankorId = $ADAT['tankorId'];
	$osztalyId = $ADAT['osztalyId'];
	$tanarId = $ADAT['tanarId'];
	$diakId = $ADAT['diakId'];
	// ---

	// tanmenet
        echo '<div style="display: none;" id="infodiv">
        <div id="infodivheader"><span id="infodivclose">X</span>'._TANMENET_RESZLETEI.'</div>';
    	    formBegin(array('action'=>href('index.php?page=naplo&sub=tanmenet&f=tanmenetInfo'), 'class'=>"onSubmitUpdate", 'id'=>"inform"));
            echo '<input type="hidden" name="tanmenetId" id="informTanmenetId" value="" />'."\n";
	    formEnd();
        echo '</div>'."\n";

	// tankör haladási
        echo '<div style="display: none;" id="haladdiv">
        <div id="haladdivheader"><span id="haladdivclose">X</span>'._TANKOR_HALADASI.'</div>';
    	    formBegin(array('action'=>href('index.php?page=naplo&sub=haladasi&f=haladasi'), 'class'=>"onSubmitUpdate", 'id'=>"haladform"));
            echo '<input type="hidden" name="tankorId" id="haladformTankorId" value="" />'."\n";
	    formEnd();
        echo '</div>'."\n";


	if ($ADAT['title']=='') return;

	$FORM = array('action'=>href('index.php?page=naplo&sub=haladasi&f=haladasi'), 'name'=>'haladasiOrabeiras', 'class'=>'');
	formBegin($FORM);
	    echo '<input type="hidden" name="igDt" value="'._SHOW_DAYS_TO.'" />'."\n";
	    echo '<input type="hidden" name="osztalyId" value="'.$osztalyId.'" />'."\n";
	    echo '<input type="hidden" name="diakId" value="'.$diakId.'" />'."\n";
	    echo '<input type="hidden" name="tanarId" value="'.$tanarId.'" />'."\n";
	    echo '<input type="hidden" name="order" value="'.$order.'" />'."\n";
	    echo '<input type="hidden" name="action" value="haladasiNaploBeiras" />'."\n";
	    if ($tankorId != '') echo '<input type="hidden" name="tankorId" value="'.$tankorId.'" />'."\n";

            if (_SHOW_DAYS_FROM > $_TANEV['kezdesDt']) echo '<input class="gomb" type="submit" name="lapoz" value="<<" tabindex="5" />'."\n";
            echo ' '._IDOSZAK.': '.str_replace('-','.',_SHOW_DAYS_FROM) . '. - '. str_replace('-','.', _SHOW_DAYS_TO) .'. '."\n";
            if (_SHOW_DAYS_TO < date('Y-m-d'))  echo '<input class="gomb" type="submit" name="lapoz" value=">>" tabindex="6" />'."\n";
	    echo '<br />';
	
	// -------------------------------
	$toTime = strtotime(_SHOW_DAYS_TO);
	$fromTime = strtotime(_SHOW_DAYS_FROM);

	if ($order == 'ASC') {
	    for ($time = $fromTime; $time <= $toTime; $time = strtotime('1 day',$time)) {

		$dt = date('Y-m-d',$time);
		$count = count($data[$dt]);
		if ($tankorId == '') {
		    putNap($dt, $data[$dt], $data['napok'][$dt], $data['dolgozatok'], $ADAT['tanitasiNap'][$dt]);
		} elseif ($count > 0) {
		    putTankorNap($dt, $data[$dt], $data['dolgozatok'], $order);
		} // kirakjuk-e a napot

	    } // for $dt
	} else {
	    for ($time = $toTime; $time >= $fromTime; $time = strtotime('-1 day',$time)) {

		$dt = date('Y-m-d',$time);
		$count = count($data[$dt]);
		if ($tankorId == '') {
		    putNap($dt, $data[$dt], $data['napok'][$dt], $data['dolgozatok'], $ADAT['tanitasiNap'][$dt]);
		} elseif ($count > 0) {
		    putTankorNap($dt, $data[$dt], $data['dolgozatok'], $order);
		} // kirakjuk-e a napot

	    } // for $dt
	}
	// ---------------------------------

	formEnd();

    }


    function putNap($dt, $dNap, $napInfos, $doga, $napInfo2) {

        global $aHetNapjai,$ADAT;

	$time = strtotime($dt);
	$count = count($dNap);

	$tipus = $orarendiHet = $megjegyzes = array();
	if (is_array($napInfos)) foreach ($napInfos as $ni) {	
	    if (!in_array($ni['tipus'], $tipus)) $tipus[] = $ni['tipus']; 
	    if ($ni['orarendiHet'] != 0 && !in_array($ni['orarendiHet'], $orarendiHet)) $orarendiHet[] = $ni['orarendiHet']; 
	    if ($ni['megjegyzes'] != '' && !in_array($ni['megjegyzes'], $megjegyzes)) $megjegyzes[] = $ni['megjegyzes']; 
	}
	$tanitasiNap = false;
	if (in_array('tanítási nap', $tipus) || in_array('speciális tanítási nap', $tipus)) {
	    $tanitasiNap = true;
	}


	    echo '<h2>';
		echo str_replace('-','.',$dt) .'. '. $aHetNapjai[date('w',$time)-1];
		if ($napInfo2['napszam']!='' || $napInfo['orarendiHet'] != 0) echo ' (';
		    if ($tanitasiNap) {
			echo $napInfo2['napszam'] . '. ' . _TANITASI_NAP;
			if ($napInfo['orarendiHet'] != 0) echo '/';
		    }
		    if (count($orarendiHet) > 0) echo ' - '.implode('./',$orarendiHet).'. '._HET;
		    if (count($megjegyzes) > 0) echo ' - '.implode('/', $megjegyzes);
		if ($napInfo2['napszam']!='' || $napInfo['orarendiHet'] != 0) echo ')';
	    echo '</h2>';

	putHaladasiDolgozat($dt,$doga);

	$o = 0;
	$_UJORA = array();
	if ($count > 0) {
	    for ($i=0; $i<$count; $i++) {
                while ($o < $dNap[$i]['ora']) {
                    if (__PLUSZBEIRHAT===true) $_UJORA[] = array('dt'=>$dt, 'ora'=>intval($o));
                    $o++;
                }
                $o=$dNap[$i]['ora']+1;
		putOra($dNap[$i]);
	    } // órák kiírása
            for($j=$dNap[$i-1]['ora']+1; $j<=$ADAT['maxOra']; $j++) {
                if (__PLUSZBEIRHAT===true) $_UJORA[] =array('dt'=>$dt, 'ora'=>$j);
            }
	} else {
	    echo _NINCS_ORAJA.'<br />';
	    for($j=1; $j<=$ADAT['maxOra']; $j++) {
                    if (__PLUSZBEIRHAT===true) $_UJORA[] = array('dt'=>$dt, 'ora'=>$j);
            }
	}
	echo '<h3>'._PLUSZ_FELADATOK.'</h3>';
	echo '<ul>';
		for($i=0; $i<count($_UJORA); $i++) putUjOra($_UJORA[$i]);
	echo '</ul>';
    }


    function putTankorNap($dt, $dNap, $doga, $order) {

	$time = strtotime($dt);
	$count = count($dNap);
	
	putHaladasiDolgozat($dt,$doga);

	for ($i=0; $i<$count; $i++) {
	    if ($order == 'DESC') putTankorOra($dNap[$count-$i-1]);
	    else  putTankorOra($dNap[$i]);
	} // órák kiírása

    }


    function putHaladasiDolgozat($dt,$doga) {

	for ($i=0;$i<count($doga['tervezett'][$dt]);$i++) {
	    $did = $doga['tervezett'][$dt][$i];
	    echo '<p class="dolgozat">';
		$href = href('index.php?page=naplo&sub=osztalyozo&f=dolgozat&dolgozatId='.$did);
		echo '<a href="'.$href.'">';
	    	echo _BEJELENTETT_DOLGOZAT . ': '. $doga[$did]['dolgozatNev'];
		echo ' (' ;
		for ($j=0;$j<count($doga[$did]['tankor']);$j++) {
		    if ($j != 0) echo ', ';
		    echo $doga[$did]['tankor'][$j]['tankorNev'];
		}
		echo ')';
		echo '</a>';
	    echo '</p>';
	}

    }

    function putOra($dOra) {

	global $ADAT; // --FIXME
	$modosithatoOra = modosithatoOra($dOra);
	if (!in_array($dOra['tipus'],array('normál','normál máskor'))) {
	    if ($dOra['tipus'] == 'összevonás') $tipus = 'Ö';
	    else $tipus = nagybetus(substr($dOra['tipus'],0,1));
	    $tr_class = ' class="helyettesit"';
	} else {
	    $tipus = '';
	    $tr_class = '';
	}
	echo '<div'.$tr_class.'>';

	    // ----- óra ----------------------------------
	    echo $dOra['ora'].'. '._ORA.': ';

	    // ----- Tankör -------------------------------
		// -------------------------------------------------------------------------
		// Csoportok kezelése - Váltható tankörök (egy csoportba és egy tanárhoz tartozó tankörök
		// -------------------------------------------------------------------------
			if (
				in_array($dOra['tipus'],array('normál','normál máskor')) // helyettesített óra esetén ne lehessen váltani - bár kirakná a selectet jól...
				&& is_array($dOra['csoport']) && count($dOra['csoport'])>1
				&& $modosithatoOra
			) {

				echo '<select title="'._TANKOR.'" name="M_'.$dOra['oraId'].'">';
				for ($t = 0; $t < count($dOra['csoport']); $t++) {
				    if ($dOra['tankorId'] == $dOra['csoport'][$t]['tankorId']) $__SEL = ' selected="selected" ';
				    else $__SEL = '';
				    echo '<option value="'.$dOra['csoportId'].':'.$dOra['csoport'][$t]['tankorId'].'" '.$__SEL.'>';
					echo $dOra['csoport'][$t]['tankorNev'];
				    echo '</option>';
				}
				// Ha egy másik tanár helyettesít, akinek vannak órái ugyanabból a tankör csoportból - akkor a jelenlegi tankorId nincs a select-ben még!
				if ($__SEL == '') echo '<option value="'.$dOra['csoportId'].':'.$dOra['tankorId'].' selected="selected">'.$dOra['tankorNev'].'</option>';
				echo '</select>';
			} else { // nincs választási lehetőség, vagy a módosítási határidő lejárt
			    echo $dOra['tankorNev'];
			}
			echo '<input type="hidden" name="tanmenetIdContainer[]" value="'.$ADAT['tankorTanmenet'][ $dOra['tankorId'] ].'" />'."\n";
			echo '<input type="hidden" name="tankorIdContainer[]" value="'.$dOra['tankorId'].'" />'."\n";
		// -------------------------------------------------------------------------	
			
	    // ----- Tanár(ok) -------------------------------
		// Ha egy normál órának több tanára is van, és módosítható az óra, akkor lehet választani a tanárok közül
/*
		if (count($dOra['tanar']) > 1 && in_array($dOra['tipus'],array('normál','normál máskor')) && $modosithatoOra) {
		    $_SEL = array($dOra['ki'] => 'selected="selected" ');
		    echo '<select title="'._TANAR.'" name="K_'.$dOra['oraId'].'">'."\n";
		    for ($t = 0; $t < count($dOra['tanar']); $t++) {
			echo '<option value="'.$dOra['tanar'][$t]['tanarId'].'" '.$_SEL[$dOra['tanar'][$t]['tanarId']].'>';
			echo $dOra['tanar'][$t]['tanarNev'];
			echo '</option>'."\n";
		    }
		    echo '</select>';
		} else {
		    echo $dOra['kiCn'];
		}
*/
		echo ' - '.$dOra['oraszam'].'. '._ORA.'<br />';

	    // ----- Leírás ---------------------------------
		if ($modosithatoOra) {
		    if ($dOra['leiras']!='') { // beírva
			echo '<input type="text" tabindex="1" name="L_'.($dOra['oraId']).'" class="data beirva" size="30" value="'.htmlspecialchars($dOra['leiras']).'" />';
			echo '<input type="submit" class="gomb" value="'._MODOSIT.'" tabindex="1" />';
		    } else {
			echo '<input type="text" tabindex="1" name="L_'.($dOra['oraId']).'" class="data" size="30" value="'.htmlspecialchars($dOra['leiras']).'" />';
			echo '<input type="submit" class="gomb" value="'._ROGZIT.'" tabindex="1" />';
		    }
		    echo '<input type="hidden" name="oraId[]" value="'.$dOra['oraId'].'" />';
		} else {
		    if ($dOra['leiras']!='') {
    			echo $dOra['leiras'];
		    } else {
			echo _NINCS_BEIRVA;
		    }
		}
		echo '<br />';
	    // ----- Hiányzók -------------------------------
		if ( __DIAK) {
		    $href = href('index.php?page=naplo&sub=hianyzas&f=diak&dt='.$dOra['dt'].'&diakId='.$diakId);
		} else {
		    $href = href('index.php?page=naplo&sub=hianyzas&f=ora&oraId='.$dOra['oraId']);				
		}
		echo '<a href="'.$href.'" tabindex="200">';
		    echo _HIANYZOK;
		echo '</a>';
	echo '</div>';
    }


    function putTankorOra($dOra) {

        global $aHetNapjai;

	$modosithatoOra = modosithatoOra($dOra);
		
	if (!in_array($dOra['tipus'],array('normál','normál máskor'))) {
//	if (substr($dOra['tipus'],0,6) != 'normál') {
	    $tipus = nagybetus(substr($dOra['tipus'],0,1));
	    $tr_class = ' class="helyettesit"';
	} else {
	    $tipus = '';
	    $tr_class = '';
	}

	echo '<div'.$tr_class.'>';

	    // ----- óra ----------------------------------
		echo str_replace('-','.',$dOra['dt']) .'. '. $aHetNapjai[date('w',strtotime($dOra['dt']))-1].' ';
		echo $dOra['ora'].'. '._ORA.': ';

	    // ----- Tankör -------------------------------
		// -------------------------------------------------------------------------
		// Csoportok kezelése - Váltható tankörök (egy csoportba és egy tanárhoz tartozó tankörök
		// -------------------------------------------------------------------------
			if (
				in_array($dOra['tipus'],array('normál','normál máskor')) // helyettesített óra esetén ne lehessen váltani - bár kirakná a selectet jól...
				&& is_array($dOra['csoport']) && count($dOra['csoport']) > 1
				&& $modosithatoOra
			) {
				echo '<select name="M_'.$dOra['oraId'].'">';
				for ($t = 0; $t < count($dOra['csoport']); $t++) {
				    if ($dOra['tankorId'] == $dOra['csoport'][$t]['tankorId']) $__SEL = ' selected="selected" ';
				    else $__SEL = '';
				    // !?! A másik függvényben a csoportId-t is átadjuk - nem hiba???
				    echo '<option value="'.$dOra['csoport'][$t]['tankorId'].'" '.$__SEL.'>';
					echo $dOra['csoport'][$t]['tankorNev'];
				    echo '</option>';
				}
				echo '</select>';
				// Ha egy másik tanár helyettesít, akinek vannak órái ugyanabból a tankör csoportból - akkor a jelenlegi tankorId nincs a select-ben még!
				// !?! A másik függvényben a csoportId-t is átadjuk - nem hiba???
				if ($__SEL == '') echo '<option value="'.$dOra['tankorId'].' selected="selected">'.$dOra['tankorNev'].'</option>';
			} else { // nincs választási lehetőség, vagy a módosítási határidő lejárt
			    echo $dOra['tankorNev'];
			}
		// -------------------------------------------------------------------------	

/*
	    // ----- Tanár(ok) -------------------------------
		// Ha egy normál órának több tanára is van, és módosítható az óra, akkor lehet választani a tanárok közül
		if (count($dOra['tanár']['id']) > 1 and $modosithatoOra) {
		    $_SEL = array($dOra['kiId'] => 'selected="selected" ');
		    echo '<select name="K_'.$dOra['oraId'].'">'."\n";
		    for ($t=0;$t<count($dOra['tanár']['id']);$t++) {
			echo '<option value="'.$dOra['tanár']['id'][$t].'" '.$_SEL[$dOra['tanár']['id'][$t]].'>';
			echo $dOra['tanár'][$dOra['tanár']['id'][$t]]['cn'];
			echo '</option>'."\n";
		    }
		    echo '</select>';
		} else {
		    echo $dOra['kiCn'];
		}
*/
		echo ' - '.$dOra['oraszam'].'. '._ORA.'<br />';

	    // ----- Leíráás ---------------------------------
		if ($modosithatoOra) {
		    if ($dOra['leiras']!='') { // beírva
			echo '<input type="text" tabindex="1" name="L_'.($dOra['oraId']).'" class="data beirva" size="30" value="'.htmlspecialchars($dOra['leiras']).'" />';
			echo '<input type="submit" class="gomb DOA" value="'._MODOSIT.'" />';
		    } else {
			echo '<input type="text" tabindex="1" name="L_'.($dOra['oraId']).'" class="data" size="30" value="'.htmlspecialchars($dOra['leiras']).'" />';
			echo '<input type="submit" class="gomb DOA" value="'._ROGZIT.'"  />';
		    }
		    echo '<input type="hidden" name="oraId[]" value="'.$dOra['oraId'].'" />';
		} else {
		    if ($dOra['leiras']!='') {
			echo $dOra['leiras'];
		    } else {
			echo _NINCS_BEIRVA;
		    }
		}
	    echo '<br />'."\n";

	    // ----- Hiányzók -------------------------------
		if ( __DIAK) {
		    $href = href('index.php?page=naplo&sub=hianyzas&f=diak&dt='.$dOra['dt'].'&diakId='.$diakId);
		} else {
		    $href = href('index.php?page=naplo&sub=hianyzas&f=ora&oraId='.$dOra['oraId']);				
		}
		echo '<a href="'.$href.'">';
		    echo _HIANYZOK;
		echo '</a>';

	echo '</div>'."\n";


    }

    function putHetesForm($ADAT) {

	formBegin(array('class'=>'hetes'));
	    echo '<input type="hidden" name="igDt" value="'._SHOW_DAYS_TO.'" />'."\n";
	    echo '<input type="hidden" name="osztalyId" value="'.$ADAT['osztalyId'].'" />'."\n";
	    echo '<input type="hidden" name="dt" value="'._SHOW_DAYS_FROM.'" />'."\n";
	    echo '<input type="hidden" name="action" value="hetesFelvetel" />'."\n";

	    echo '<span>'._HETESEK.'</span>';
	    for ($k = 1; $k < 3; $k++) {
		$SEL = array($ADAT['hetesek'][$k]['diakId'] => ' selected="selected" ');
		echo '<select name="hetes'.$k.'">'."\n";
		    echo '<option value=""> - </option>'."\n";
		for ($i = 0; $i < count($ADAT['diakok']); $i++) {
		    echo '<option value="'.$ADAT['diakok'][$i]['diakId'].'"'.$SEL[ $ADAT['diakok'][$i]['diakId'] ].'>'.$ADAT['diakok'][$i]['diakNev'].'</option>'."\n";
		}
		echo '</select>'."\n";
	    }

	    echo '<input type="submit" value="'._OK.'" />'."\n";

	formEnd();

    }

    function putUjOra($dOra) {

        global $ADAT; // --FIXME

        if (__TANAR !==true && __VEZETOSEG!==true && __NAPLOADMIN !== true) return false;
        if (__NAPLOADMIN ===true || __VEZETOSEG===true) {
            $_eredet='órarend';
            if (__PLUSZBEIRHAT!==true
                || strtotime($dOra['dt'])>strtotime("+1week")
                || (__TANAR ===true && strtotime(_HALADASI_HATARIDO)>strtotime($dOra['dt']))
            ) return false;
        } else {
            $_eredet='plusz';
            if (__PLUSZBEIRHAT!==true
                || strtotime($dOra['dt'])>time()
                || (__TANAR ===true && strtotime(_HALADASI_HATARIDO)>strtotime($dOra['dt']))
            ) return false;
        }
       $_tipus='egyéb';

            echo '<li class="ora">';
                echo $dOra['ora'].'.';
                echo '<select class="DOA" name="UJORA[]" tabindex="1" >';
                echo '<option value="">'._FELADAT_TIPUS.'</option>';
                if (is_array($ADAT['feladatTipus'])) foreach($ADAT['feladatTipus'] as $feladatTipusId=>$_D) {
                    echo '<option value="'.$dOra['dt'].'_'.$dOra['ora'].'_'.$_tipus.'_'.$_D['feladatTipusId'].'">'.$_D['feladatTipusLeiras'].' ('.$_D['feladatTipusId'].')</option>';
                }
                echo '</select>';
                //echo $ADAT['feladatTipus'][$dOra['feladatTipusId']]['feladatTipusLeiras'].' ('.$dOra['eredet'].')';
                echo '<br/>';
		echo '<input type="text" tabindex="1" name="LE_'.($dOra['dt'].'_'.$dOra['ora']).'" class="data"  value="'.htmlspecialchars($dOra['leiras']).'" />';
		echo '<input type="submit" value="'._ROGZIT.'" class="gomb DOA" tabindex="1" />';
	    echo '</li>';
    }

?>
