<?php

    function putHirek($ADAT) {

	if (count($ADAT['hirek']['szovegek'])==0) {

	    if (_POLICY=='public') {
		echo '<div style="width:100%;  color:#eee; text-align:center;margin-top:40px;margin-bottom:40px;"><span style="font-size:120px;" class="icon-eye-close"></span><br/>Nincs aktuális hír</div>';
	    }

	} else {

	  $KATEGORIAID2LEIRAS = (reindex($ADAT['kategoriak'],array('id')));

	  if ($ADAT['kategoriaId']>0 && $KATEGORIAID2LEIRAS[$ADAT['kategoriaId']][0]['leiras']!='') {
		echo '<h2 class="hirKategoriaSelected">';
		    echo ucfirst($KATEGORIAID2LEIRAS[$ADAT['kategoriaId']][0]['leiras']);
		    echo '<a href="'.href('index.php?page=portal&f=portal&sub=portal').'" class="icon-remove-sign"></a>';
		echo '</h2>';
	  }

	  for ($i=0; $i<count($ADAT['hirek']['szovegek']); $i++) {

	    $D = $ADAT['hirek']['szovegek'][$i];
	    $_class = ($D['class']==6 && _POLICY!='public') ? 'asPrivate':'';
	    list ($a,$b) = explode('<!-- more -->',$D['txt']);

	    echo '<div class="egyHir '.$_class.'">';
	    if ($D['cim']!='') {
		echo '<div class="hirCim">';
		if ($D['class']==6) {
		    echo '<span title="Védett hír" class="icon-lock-alt" style="padding-right:4px;"></span>';
		}
		echo '<a href="'.href('index.php?page=portal&sub=portal&f=hir&hirId='.$D['id']).'">'.$D['cim'].'</a>';
		echo '</div>';
		echo '<div class="egyHirmeta" style="color:#aaa; padding:0px 2px 6px 0px; font-size:x-small;">';
		    echo superdate($D['kdt']);
		    echo ' · ';
		    echo $D['owner'];
		    if ($D['csoport']!='') {
			$CSOPORT = explode(',',$D['csoport']);
			echo ' · ';
			//echo '<span style="margin-top:10px">';
			for ($j=0; $j<count($CSOPORT); $j++) echo '<span class="tag">'.$CSOPORT[$j].'</span>';
			//echo '</span>';
		    }
		    if ($D['hirkategoriak']!='') {
			$D['kategoriaIdk'] = explode(',',$D['hirkategoriak']);
			for ($j=0; $j<count($D['kategoriaIdk']); $j++ ) {
			    echo ' · ';
			    echo '<a href="'.href('index.php?page=portal&sub=portal&f=portal&kategoriaId='.$D['kategoriaIdk'][$j]).'" class="hirkategoriaLeiras">'.$KATEGORIAID2LEIRAS[$D['kategoriaIdk'][$j]][0]['leiras'].'</a>';
			}
		    }
		echo '</div>';
	    }
	    echo '<div class="hir">';
		echo $a;
		if ($b!="") echo ' <a href="'.href('index.php?page=portal&sub=portal&f=hir&hirId='.$D['id']).'">Tovább...</a>';
	    echo '</div>';
	    for ($j=0; $j<count($ADAT['hirek']['linkek'][$D['id']]); $j++) {
		echo '<a href="'.$ADAT['hirek']['linkek'][$D['id']][$j]['uri'].'">';
		echo $ADAT['hirek']['linkek'][$D['id']][$j]['szoveg'];
		echo '</a>';
	    }

	    echo '<div style="display:none; font-size:10px; padding:2px; text-align:right; color:#aaa">'.($ADAT['hirek']['szovegek'][0]['kdt']).'</div>';
	    echo '<hr style="clear:both; height:0px; margin-top:2em; margin-bottom:2em; width:80%; background-color: #777777; border-style: solid; border-color: #eeeeee; border-width: 0px 0px 1px 0px;" />';
	    echo '</div>';
	  }
	}
    }

?>
