<?php
/*
    Module: base
    
    js_alert()
    html_alert()
*/

// ------------------------------------------------------------------- //
// Az $_SESSION['alert'] két részből áll: típus:hiba                               //
// típus: alert   : javaScript alert                                   //
//	  message : hibaüzenet után az oldal betöltődik                //
//	  page    : hibaüzenet után az oldal nem töltődik be           //
//	  info    : információs üzenet                                 //
// ------------------------------------------------------------------- //

// ---------------------------------------------------------------- //
//  Hibaüzenet kiiratása 
//  visszatérési érték: legyen-e utána megjelenítve a lap?
// --------------------------------------------------------------- //

    function html_alert() {

	global $ALERT_MSG;

	if (!isset($_SESSION['alert']) || count($_SESSION['alert'])==0) {
	    return true;
	    exit;
	}

	$showPage = true;
	echo '<form method="post" action="" class="mayorAlert" id="mayorAlert">';
	for ($j = 0; $j < count($_SESSION['alert']); $j++) {

	    // Nincs mindig paraméter - ezért a $param nem kap értéket! - így az explode Notice üzenetet váltana ki...
	    $param = array();
	    $tmp = explode(':',$_SESSION['alert'][$j]);
	    $aType = $tmp[0]; $aCode = $tmp[1];
	    for ($p = 2; $p < count($tmp); $p++) $param[] = $tmp[$p];
	    $pstr = '';
	    if ($aType == 'popup') {
		if ($aCode == '' ) $msg = $ALERT_MSG['default'];
		elseif ($ALERT_MSG[$aCode] == '') $msg = $aCode;
		else $msg = $ALERT_MSG[$aCode];
		// paraméter behelyettesítés
		for($i = 1; $i < count($param); $i++) {
		    $msg = str_replace("%$i%",$param[$i],$msg,$count);
		    if ($param[$i] != '' and $count == 0) $pstr .= $param[$i].',';
		}
		if ($pstr != '') $msg .= ' (' . substr($pstr,0,-1) . ')';

		echo '<input type="hidden" name="jsAlert" value="'.$msg.'" />';
	    } else {	    
		if ($aCode == '') $msg = $ALERT_MSG['default'];
		elseif (!isset($ALERT_MSG[$aCode]) || $ALERT_MSG[$aCode] == '') $msg = $ALERT_MSG['default'].' (<span class="alertParam">'.$aType.':'.$aCode.')</span>';
		else $msg = $ALERT_MSG[$aCode];
		// paraméter behelyettesítés
		for($i = 0; $i < count($param); $i++) {
		    $_msg = $msg;
		    $msg = @str_replace("%$i%",'<span class="alertParam">'.$param[$i].'</span>',$msg);
		    if ($param[$i] != '' and $_msg == $msg) $pstr .= '<span class="alertParam">'.$param[$i].'</span>,';
		}
		if ($pstr != '') $msg .= ' (' . substr($pstr,0,-1) . ')';

		if (($aType == 'message') or ($aType == 'page')) {
		    $title = _ERROR;
		    $class = 'errorMsg';
		    if ($aType == 'page') $showPage = false;
		} else {
		    $title = _INFORMATION;
		    $class = 'infoMsg';
		}
		$msg = '<span>'.$title.':</span> ' . $msg;
		echo '<div class="'.$class.'">'.$msg.'</div>'."\n";

	    }
	    $_SESSION['alert'] = array();
	}
	echo '</form>';

	return $showPage;

    }

?>
