<?php

    function generateFutarEmailTorzs($ADAT) {

	if (!is_array($ADAT['hirnokFolyam'])) return false; 

	for ($h=0; $h<count($ADAT['hirnokFolyam']); $h++) {
	  if (count($ADAT['hirnokFolyam'])>1) { // csak ha nem egyértelmű
	    $RETURN_STR .= '<div class="hirnokSeparator">';
		// putFace($ADAT['hirnokFolyam'][$h]['hirnokFolyamAdatok']['id'],$ADAT['hirnokFolyam'][$h]['hirnokFolyamAdatok']['tipus'],30);
		$RETURN_STR .= '<a href="'.href('index.php?page=naplo&sub=hirnok&f=hirnok').'">'.$ADAT['hirnokFolyam'][$h]['hirnokFolyamAdatok']['cn'].'</a>';
	    $RETURN_STR .= '</div>';
	  }
	  foreach ($ADAT['hirnokFolyam'][$h]['hirnokFolyamUzenetek'] as $stamp => $DA) {
	    for ($i=0; $i<count($DA); $i++) {
		$D = $DA[$i];
		$RETURN_STR .= '<div class="hirnokDoboz '.$D['hirnokTipus'].'">';
		    $RETURN_STR .= '<div class="hirnokBadgeHolder '.$D['hirnokTipus'].'">';
			if (function_exists('generateFutarBadge_'.$D['hirnokTipus'])) $RETURN_STR .= call_user_func('generateFutarBadge_'.$D['hirnokTipus'],$D);
		    $RETURN_STR .= '</div>';
		    $RETURN_STR .= '<div class="hirnokDt">';
			if (function_exists('generateFutarDetail_'.$D['hirnokTipus'])) $RETURN_STR .= call_user_func('generateFutarDetail_'.$D['hirnokTipus'],$D);
			else $RETURN_STR .= (date('Y.m.d. H:i:s',$stamp));
		    $RETURN_STR .= '</div>';
		    $RETURN_STR .= '<div class="hirnokText '.$D['hirnokTipus'].'">';
			if (function_exists('generateFutar_'.$D['hirnokTipus'])) $RETURN_STR .= call_user_func('generateFutar_'.$D['hirnokTipus'],$D);
			// else dump($D);
		    $RETURN_STR .= '</div>';
		    $RETURN_STR .= '<div class="hirnokRight '.$D['hirnokTipus'].'">';
			if (function_exists('generateFutarRight_'.$D['hirnokTipus'])) $RETURN_STR .= call_user_func('generateFutarRight_'.$D['hirnokTipus'],$D);
		    $RETURN_STR .= '</div>';
/*		    $RETURN_STR .= '<div class="hirnokFooter '.$D['hirnokTipus'].'">';
			if (function_exists('generateFutarFooter_'.$D['hirnokTipus'])) $RETURN_STR .= call_user_func('generateFutarFooter_'.$D['hirnokTipus'],$D);
		    $RETURN_STR .= '</div>';
*/
		$RETURN_STR .= '</div>';
	    }
	  }
	}
	// vege $RETURN_STR .= '<div class="hirnokSeparator"><a href="'.href('index.php?page=naplo&sub=hirnok&f=hirnok').'"><span class="icon-calendar"></span> '.superdate($ADAT['tolDt']).'<span class="icon-bullhorn"></span></a></div>';
	return str_replace('</div>','</div>'."\n",$RETURN_STR);
    }
    function generateFutarRight_uzeno($D) {
	return $RETURN_STR;
    }
    function generateFutarFooter_uzeno($D) {
	return $RETURN_STR;
    }
    function generateFutar_idoszak($D) {
	$RETURN_STR .= 'Aktív <b>'.$D['idoszakAdat']['tipus'].'</b> időszak: '.$D['idoszakAdat']['tolDt'].' – '.$D['idoszakAdat']['igDt'];
	return $RETURN_STR;
    }

    function generateFutar_utolsoora($D) {
       $a_az[0] = 'a';
        $a_az[1] = 'az';
        $a_az[2] = 'a';
        $a_az[3] = 'a';
        $a_az[4] = 'a';
        $a_az[5] = 'az';
        $a_az[6] = 'a';
        $a_az[7] = 'a';
        $a_az[8] = 'a';
        $a_az[9] = 'a';
        $a_az[10] = 'a';
        $a_az[11] = 'a';
        $a_az[12] = 'a';
        $RETURN_STR .='Ma a haladási napló szerint a(z) <b>'.$D['adat']['teremNev'].'</b> teremben '.$a_az[$D['adat']['utolsooraateremben']].' <b>'.$D['adat']['utolsooraateremben'].'. óra</b> után már nincs óra!';
	return $RETURN_STR;
    }

    function generateFutarBadge_jegy($D) {
	// return '<i class="material-icons">face</i>';
    }

   function generateFutar_haladasiOra($D) {
        global $aHetNapjai;
        $nap = kisbetus($aHetNapjai[date('w',strtotime($D['oraAdat']['dt']))-1]);
        $RETURN_STR .= 'A '.$D['oraAdat']['tankorCn'].' tankör '.$D['oraAdat']['dt'].' '.$nap.'i '.$D['oraAdat']['ora'].'. óra státusza megváltozott. ';
	if ($D['oraAdat']['teremId']>0) $RETURN_STR .= 'Terme: '.$D['oraAdat']['teremLeiras'].' ('.$D['oraAdat']['teremId'].') ';
        $RETURN_STR .= 'Új típusa: <b>'.$D['oraAdat']['tipus'].'</b>! ';
        if ($D['oraAdat']['ki']>0) $RETURN_STR .= '('.$D['oraAdat']['kiCn'].')';
	return $RETURN_STR;
    }

    function generateFutarDetail_uzeno($D) {
	$IMG = array( // jobb lenne valami shared helyen
            'diak' => '<span title="diák" class="icon-child"></span>',
            'szulo' => '<span title="szülő"  class="icon-adult"></span>',
            'tanar' => '<span title="tanár"  class="icon-adult"></span>',
            'munkakozosseg' => '<span title="munkaközösség tagjai" class="icon-slideshare"></span>',
            'tankor' => '<span  title="tankör diákjai és tanára" class="icon-myspace"></span>',
            'tankorSzulo' => '<span title="tankörbe járók szülei"  class="icon-group-alt"></span>',
            'osztaly' => '<span  title="osztály diákjai és osztályfőnökei" class="icon-group"></span>',
            'osztalySzulo' => '<span title="osztályba járók szülei"  class="icon-adult"></span>',
            'osztalyTanar' => '<span title="osztályban tanítók"  class="icon-slideshare"></span>',
	);
	$TIPUS_STR = array(
            'diak' => 'diák',
            'szulo' => 'szülő',
            'tanar' => 'tanár',
            'munkakozosseg' => 'munkaközösség tagjai',
            'tankor' => 'tankör diákjai és tanára',
            'tankorSzulo' => 'tankörbe járók szülei',
            'osztaly' => 'osztály diákjai és osztályfőnökei',
            'osztalySzulo' => 'osztályba járók szülei',
            'osztalyTanar' => 'osztályban tanítók',
	);
	$_szalId = $D['uzenoAdat']['feladoId'].'_'.$D['uzenoAdat']['feladoTipus'].'_'.$D['uzenoAdat']['cimzettId'].'_'.$D['uzenoAdat']['cimzettTipus'];
	$_link1 = href('index.php?page=naplo&sub=uzeno&f=uzeno&feladoId='.$D['uzenoAdat']['feladoId'].'&feladoTipus='.$D['uzenoAdat']['feladoTipus']);
	$_link2 = href('index.php?page=naplo&sub=uzeno&f=uzeno&cimzettId='.$D['uzenoAdat']['cimzettId'].'&feladoTipus='.$D['uzenoAdat']['cimzettTipus']);
	$RETURN_STR .= '<a href="'.$_link1.'">';
	    if ($D['uzenoAdat']['feladoId']==0) $RETURN_STR .= 'Adminisztrátor';
	    else $RETURN_STR .= $D['feladoNev'];
	$RETURN_STR .= '</a>';
	//TESZT	$RETURN_STR .= '<span class="icon-caret-right" style="padding: 0px 4px; font-size:8px;"></span>';
	if ($D['cimzettNev']!='') $RETURN_STR .= '<br/><span><a href="'.$_link2.'">'.$D['cimzettNev'].'</a></span>';
	$RETURN_STR .= '<br/>';
	$RETURN_STR .= '<span style="color:#aaa;">';
	$RETURN_STR .= superdate(date('Y-m-d H:i:s',strtotime($D['uzenoAdat']['dt'])));
	$RETURN_STR .= '<span style="padding: 0px 2px;">·</span>';
	    if ($D['uzenoAdat']['cimzettId']==0) $RETURN_STR .= '<span class="icon-globe" title="minden"></span>';
	    else $RETURN_STR .= $IMG[$D['uzenoAdat']['cimzettTipus']];
	$RETURN_STR .= '<span style="padding: 0px 2px;">·</span>';
	    if ($D['uzenoAdat']['cimzettId']==0) $RETURN_STR .= 'minden ';
	    $RETURN_STR .= $TIPUS_STR[$D['uzenoAdat']['cimzettTipus']];
	$RETURN_STR .= '</span>';
	return $RETURN_STR;

    }

    function generateFutar_zaroJegy($D) {
	global $KOVETELMENY;

	$RETURN_STR .= ucfirst($D['targyAdat']['targyNev']);
	$RETURN_STR .= ' tárgyból ';

	$RETURN_STR .= $D['zaroJegyAdat']['evfolyamJel'].'. évfolyam ';
	$RETURN_STR .= ''.$D['zaroJegyAdat']['felev'].'. félévére ';

	$RETURN_STR .= '<b>'.($KOVETELMENY[$D['zaroJegyAdat']['jegyTipus']][$D['zaroJegyAdat']['jegy']]['hivatalos']).'</b>';
	$RETURN_STR .= ' ('.$KOVETELMENY[$D['zaroJegyAdat']['jegyTipus']][$D['zaroJegyAdat']['jegy']]['rovid'].') ';
	$RETURN_STR .= $D['zaroJegyAdat']['jegyTipus'];
	$RETURN_STR .= ' típusú osztályzat került beírásra / módosult a bizonyítványban.';


	if (is_array($D['oraAdat'])) {
	    $RETURN_STR .= 'Az óra adatai: '.$D['oraAdat']['tankorNev'].' '. 
	    $D['oraAdat']['kiCn'].', '. 
	    $D['oraAdat']['leiras'].', '. 
	    $D['oraAdat']['dt'].' '.
	    $D['oraAdat']['ora'].'. óra.';	    
	}

	// dump($D);
	return $RETURN_STR;
    }
    function generateFutar_jegy($D) {
	global $KOVETELMENY;

	if ($D['jegyAdat']['dt'] != date('Y-m-d',strtotime($D['jegyAdat']['modositasDt']))) {

	    $str[] = 'Jegymódosítás! ';
	    $str[] = ucfirst($D['targyAdat']['targyNev']);
	    $str[] = 'tárgyból';

	    $str[] = '<b>'.($KOVETELMENY[$D['jegyAdat']['jegyTipus']][$D['jegyAdat']['jegy']]['hivatalos']).'</b>';
	    $str[] = '('.$KOVETELMENY[$D['jegyAdat']['jegyTipus']][$D['jegyAdat']['jegy']]['rovid'].') ';
	    $str[] = $D['jegyAdat']['jegyTipus'];
	    $str[] = 'típusú értékelésre módosult a '.$D['jegyAdat']['dt'].'-n kelt eredeti bejegyzés.';
	} else {
	    $str[] = ucfirst($D['targyAdat']['targyNev']);
	    $str[] = 'tárgyból';

	    $str[] = '<b>'.($KOVETELMENY[$D['jegyAdat']['jegyTipus']][$D['jegyAdat']['jegy']]['hivatalos']).'</b>';
	    $str[] = '(röviden: '.$KOVETELMENY[$D['jegyAdat']['jegyTipus']][$D['jegyAdat']['jegy']]['rovid'].')';
               if (!in_array($D['jegyAdat']['jegyTipus'],array('jegy','féljegy'))) $str[] = $D['jegyAdat']['jegyTipus'].' típusú';
            $str[] = 'értékelés került beírásra az osztályozó naplóba';

	}

	if (is_array($D['oraAdat'])) {
	    $str[] = 'Az óra adatai: '.$D['oraAdat']['tankorNev'].' '. 
	    $D['oraAdat']['kiCn'].', '. 
	    $D['oraAdat']['leiras'].', '. 
	    $D['oraAdat']['dt'].' '.
	    $D['oraAdat']['ora'].'. óra.';	    
	}

	// $RETURN_STR .= $D['jegyAdat']['jegy'];
	// $RETURN_STR .= $D['jegyAdat']['jegyTipus'];
	$RETURN_STR .= implode(' ',$str);

	// dump($D);
	return $RETURN_STR;
    }

    function generateFutar_dolgozat($D) {

	if (strtotime($D['dolgozatAdat']['tervezettDt'])>strtotime(date('Y-m-d H:i:s'))) {
	    $RETURN_STR .= 'Új dolgozat várható! ';
	} else {
	    $RETURN_STR .= 'Új dolgozat került rögzítésre. ';
	}
	$RETURN_STR .= 'A bejelentés ideje: ';
	$RETURN_STR .= $D['dolgozatAdat']['bejelentesDt'].', tervezett időpontja: ';
	$RETURN_STR .= $D['dolgozatAdat']['tervezettDt'].'. ';

	$RETURN_STR .= 'A dolgozat megnevezése: '.$D['dolgozatAdat']['dolgozatNev'].'. ';

	$RETURN_STR .= 'Érintett tankör';
	if (count($D['dolgozatAdat']['tankor'])>1) $RETURN_STR .= 'ök';
	$RETURN_STR .= ': ';
	for($i=0; $i<count($D['dolgozatAdat']['tankor']); $i++) {
	    $RETURN_STR .= ($D['dolgozatAdat']['tankor'][$i]['tankorNev']);
	    if ($i<count($D['dolgozatAdat']['tankor'])-1) $RETURN_STR .= ' ';
	}
	// dump( $D );
	return $RETURN_STR;
    }

    function generateFutarRight_haladasiBeiratlan($D) {
        global $UdvozloKep,$skin;
        if (!is_array($UdvozloKep) || count($UdvozloKep) == 0) $UdvozloKep = array('kutya','pingvin','smiley','garfield','majom');
        if ($D['db']==0) {
    	    $i = rand(0, count($UdvozloKep)-1);
    	    $RETURN_STR .= '<img src="skin/classic/module-naplo/img/anim/'.$UdvozloKep[$i].'.gif" alt="anim gif" style="height: 60px;" />';
        }
	return $RETURN_STR;
    }

    function generateFutar_haladasiBeiratlan($D) {

        if ($D['db']==0) {
            $RETURN_STR .= 'Köszönjük, hogy minden órádat beírtad!';
        } else {
	    $RETURN_STR .= 'Beíratlan órák száma: '.$D['db'];
        }
	return $RETURN_STR;
    }
    function generateFutar_uzeno($D) {
	if ($D['uzenoAdat']['flag']==1) $RETURN_STR .= '<i>– a szöveget a kérésedre elrejtettük –</i>';
	else $RETURN_STR .= nl2br(makelinksclickable((supertext($D['uzenoAdat']['txt'])))); // egyelőre nem tudunk bővebbet, mert a backend nem szolgáltat infót
/*	$RETURN_STR .= '<div class="hirnokIkonKontener" style="display: relativ; top:0px; right:0px; text-align:right;">';
	    $_szalId = $D['uzenoAdat']['feladoId'].'_'.$D['uzenoAdat']['feladoTipus'].'_'.$D['uzenoAdat']['cimzettId'].'_'.$D['uzenoAdat']['cimzettTipus'];
	    $RETURN_STR .= '<a href="'.href('index.php?page=naplo&sub=uzeno&f=uzeno&szalId='.$_szalId).'">';
	    $RETURN_STR .= '<span class="icon-pencil"></span>';
	    $RETURN_STR .= '</a>';

	    if ($D['uzenoAdat']['flag']!=1) {
		$RETURN_STR .= '<a href="'.href('index.php?page=naplo&sub=uzeno&f=uzeno&action=flagUzenet&flag=1&mId='.$D['uzenoAdat']['mId']).'"><span class="icon-eye-close"></span></a>';
	    } else {
		$RETURN_STR .= '<a href="'.href('index.php?page=naplo&sub=uzeno&f=uzeno&action=flagUzenet&flag=0&mId='.$D['uzenoAdat']['mId']).'"><span class="icon-eye-open"></span></a>';
	    }
	    if (__UZENOADMIN===true) {
		$RETURN_STR .= '<a href="'.href('index.php?page=naplo&sub=uzeno&f=uzeno&action=delUzenet&mId='.$D['uzenoAdat']['mId']).'"><span class="icon-trash-alt"></span></a>';
	    }
	$RETURN_STR .= '</div>';
*/
	return $RETURN_STR;

    }

    function generateFutar_bejegyzes($D) {
	$RETURN_STR .= 'Új '.ucfirst($D['bejegyzesAdat']['bejegyzesTipusNev']).' került rögzítésre. ';
	if ($D['bejegyzesAdat']['szoveg'] !='') $RETURN_STR .= '<q>'.$D['bejegyzesAdat']['szoveg'].'</q>';
	$RETURN_STR .= ' - '.$D['tanarAdat']['tanarNev'];
	return $RETURN_STR;
    }

    function generateFutar_hianyzas($D) {
        global $aHetNapjai;
        $nap = kisbetus($aHetNapjai[date('w',strtotime($D['hianyzasAdat']['dt']))-1]);
	$RETURN_STR .= $D['hianyzasAdat']['dt'].' '.$nap.' '.$D['hianyzasAdat']['ora'].'. órára (';
            $RETURN_STR .= $D['oraAdat']['tankorNev'].', '.$D['oraAdat']['kiCn'];
        $RETURN_STR .= ') ';
        if (in_array($D['hianyzasAdat']['tipus'],array('késés','hiányzás'))) $RETURN_STR .=  $D['hianyzasAdat']['statusz'].' ';
        if ($D['hianyzasAdat']['tipus']=='késés' && $D['hianyzasAdat']['perc']>0) $RETURN_STR .= ' '.$D['hianyzasAdat']['perc'].' perc ';
        $RETURN_STR .=  '<b>'.$D['hianyzasAdat']['tipus'].'</b> került rögzítésre.';
	return $RETURN_STR;
    }


?>