<?php

function putTanarLista($ADAT) {

    $cols=2;

    echo '<table class="tanarLista" align="center" cellpadding="1" cellspacing="1">';
    echo '<tr>';
    for($i=0; $i<count($ADAT['tanarok']); $i++) {
	$T = $ADAT['tanarok'][$i];
	echo '<td>';
	    putFace($T['tanarId'],'tanar',0);
	echo '</td><td>';
	    echo '<span class="tanarNev" data-tanarid="'.$T['tanarId'].'">'.$T['tanarNev'].'</span>';
	    if ($T['titulus']!='') echo '<div class="titulus">'.$T['titulus'].'</div>';
	    if ($T['statusz']=='külső óraadó') echo '<div class="titulus">'.$T['statusz'].'</div>';
	    if ($T['besorolas']=='Gyakornok') echo '<div class="titulus">'.lcfirst($T['besorolas']).'</div>';
	    elseif ($T['besorolas']=='Mesterpedagógus') echo '<div class="titulus">'.lcfirst($T['besorolas']).'</div>';
	    elseif ($T['besorolas']=='Pedagógus I.') echo '<div class="titulus">'.lcfirst($T['besorolas']).'</div>';
	    elseif ($T['besorolas']=='Pedagógus II.') echo '<div class="titulus">'.lcfirst($T['besorolas']).'</div>';
//	    else echo '<div class="titulus">'.lcfirst($T['besorolas']).'</div>'."\n";

	    $osztalyai = ($ADAT[$T['tanarId']]['osztalyfonok']);
	    for ($j=0; $j<count($osztalyai); $j++) {
		$_osztalyId = $osztalyai[$j];
		if ($ADAT['osztalyok'][$_osztalyId]['leiras']!='') {
		    echo '<div class="osztalyfonok">osztályfőnök '.$ADAT['osztalyok'][$_osztalyId]['osztalyJel'];
		    echo ' ('.$ADAT['osztalyok'][$_osztalyId]['leiras'].')';
		    echo '</div>';
		}
	    }
	    $munkakozossegei = ($ADAT[$T['tanarId']]['mkVez']); // vezetett
	    for ($j=0; $j<count($munkakozossegei); $j++) {
		$_mkId = $munkakozossegei[$j];
		echo '<div class="munkakozossegVezeto">';
		    echo $munkakozossegei[$j]['munkakozossegNev']. ' munkaközösség-vezető';
		echo '</div>';
	    }

	    $kepesitesei = $ADAT[$T['tanarId']]['kepesites'];
	    if (count($kepesitesei)>0) {
		echo '<div class="kepesites">';
		for ($j=0; $j<count($kepesitesei); $j++) {
		    $_k = $kepesitesei[$j];
//		    echo ' '.$ADAT['targyak'][$_targyId][0]['targyNev'].' ';
		    echo ''.$kepesitesei[$j]['kepesitesNev'];
		    if ($j+1<count($kepesitesei)) echo '<br/>'; 
		}
		echo '</div>';
	    }

	    $munkakozossegei = ($ADAT[$T['tanarId']]['munkakozosseg']);
	    echo '<div class="munkakozossegVezeto">';
	    $_MKNEV = array();
	    for ($j=0; $j<count($munkakozossegei); $j++) {
		$_mkId = $munkakozossegei[$j];
		$_MKNEV[] = $munkakozossegei[$j]['munkakozossegNev'];
	    }
	    echo implode(', ',$_MKNEV).' munkaközösségi tag';
	    echo '</div>';

	    if ($T['elerhetoseg']!='') echo '<div class="elerhetoseg"><span class="icon-phone" style="padding-right:0.4em"></span>'.$T['elerhetoseg'].'</div>';
	    if ($T['email']!='') echo '<div class="email"><span class="icon-envelope"    style="padding-right:0.4em"></span>'.$T['email'].'</div>';

	echo '</td>';
	if (($i+1) % $cols == 0 && $i!=count($ADAT['tanarok'])-1) echo '</tr><tr>';
    }
    echo '</tr>';
    echo '</table>';
}

/*
function putIntezmenyValaszto($Intezmenyek) {

	formBegin();

	echo '<input type="hidden" name="action" value="intezmenyValasztas" />'."\n";

	echo '<select name="intezmeny">'."\n";
	$SEL = array(__INTEZMENY => ' selected="selected"');

	for ($i = 0; $i < count($Intezmenyek); $i++) {

		$rovidnev = $Intezmenyek[$i]['rovidNev'];
		if ($Intezmenyek[$i]['alapertelmezett'] == 1)
		echo '<option value="'.$rovidnev.'" class="default"'.$SEL[$rovidnev].'>';
		else
		echo '<option value="'.$rovidnev.'"'.$SEL[$rovidnev].'>';

		echo $Intezmenyek[$i]['nev'].' ('.$Intezmenyek[$i]['OMKod'].')';
		echo '</option>'."\n";

	}

	echo '</select>'."\n";

	echo '<input type="submit" value="'._OK.'" />'."\n";

	formEnd();

}

function putTanevValaszto($Tanevek) {

	formBegin();

	echo '<input type="hidden" name="action" value="tanevValasztas" />'."\n";

	echo '<select name="tanev">'."\n";
	$SEL = array(__TANEV => ' selected="selected"');
	for ($i = 0; $i < count($Tanevek); $i++) {
		echo '<option value="'.$Tanevek[$i].'"'.$SEL[$Tanevek[$i]].'>';
		echo $Tanevek[$i];
		echo '</option>'."\n";
	}
	echo '</select>'."\n";

	echo '<input type="submit" value="'._OK.'" />'."\n";

	formEnd();
}
*/
?>
