<?php

function putTanarLista($ADAT) {

    echo '<table class="tanarLista" align="center" cellpadding="1" cellspacing="1">';
    echo '<tr>';
    for($i=0; $i<count($ADAT['tanarok']); $i++) {
	$T = $ADAT['tanarok'][$i];
	echo '<td>';
	    putFace($T['tanarId'],'tanar',30);
	echo '</td><td>';
	    echo '<span class="tanarNev" data-tanarid="'.$T['tanarId'].'">'.$T['tanarNev'].'</span>';
	    if ($T['titulus']!='') echo '<div class="titulus">'.$T['titulus'].'</div>';
	    if ($T['statusz']=='külső óraadó') echo '<div class="titulus">'.$T['statusz'].'</div>';
	    if ($T['besorolas']=='Gyakornok') echo '<div class="titulus">'.kisbetus($T['besorolas']).'</div>';
//	    if ($T['besorolas']=='Mesterpedagógus') echo '<div class="titulus">'.kisbetus($T['besorolas']).'</div>';

	    $osztalyai = ($ADAT['tanarOsztaly'][$T['tanarId']]);
	    for ($j=0; $j<count($osztalyai); $j++) {
		$_osztalyId = $osztalyai[$j];
		echo '<div class="osztalyfonok" style="color:#aaa; font-size:smaller">osztályfőnök '.$ADAT['osztalyok'][$_osztalyId]['osztalyJel'];
		echo ' ('.$ADAT['osztalyok'][$_osztalyId]['leiras'].')</div>';
	    }
	    $munkakozossegei = ($ADAT['tanarMunkakozosseg'][$T['tanarId']]); // vezetett
	    for ($j=0; $j<count($munkakozossegei); $j++) {
		$_mkId = $munkakozossegei[$j];
		echo '<div class="munkakozossegVezeto" style="color:#aaa; font-size:smaller">';
		    echo $munkakozossegei[$j]['munkakozossegNev']. ' munkaközösség-vezető';
		echo '</div>';
	    }
	echo '</td>';
	if (($i+1) % 3 == 0 && $i!=count($ADAT['tanarok'])-1) echo '</tr><tr>';
    }
    echo '</tr>';
    echo '</table>';
}

/*
function putIntezmenyValaszto($Intezmenyek) {

	formBegin();

	echo '<input type="hidden" name="action" value="intezmenyValasztas" />'."\n";

	echo '<select name="intezmeny">'."\n";
	$SEL = array(__INTEZMENY => ' selected="selected"');

	for ($i = 0; $i < count($Intezmenyek); $i++) {

		$rovidnev = $Intezmenyek[$i]['rovidNev'];
		if ($Intezmenyek[$i]['alapertelmezett'] == 1)
		echo '<option value="'.$rovidnev.'" class="default"'.$SEL[$rovidnev].'>';
		else
		echo '<option value="'.$rovidnev.'"'.$SEL[$rovidnev].'>';

		echo $Intezmenyek[$i]['nev'].' ('.$Intezmenyek[$i]['OMKod'].')';
		echo '</option>'."\n";

	}

	echo '</select>'."\n";

	echo '<input type="submit" value="'._OK.'" />'."\n";

	formEnd();

}

function putTanevValaszto($Tanevek) {

	formBegin();

	echo '<input type="hidden" name="action" value="tanevValasztas" />'."\n";

	echo '<select name="tanev">'."\n";
	$SEL = array(__TANEV => ' selected="selected"');
	for ($i = 0; $i < count($Tanevek); $i++) {
		echo '<option value="'.$Tanevek[$i].'"'.$SEL[$Tanevek[$i]].'>';
		echo $Tanevek[$i];
		echo '</option>'."\n";
	}
	echo '</select>'."\n";

	echo '<input type="submit" value="'._OK.'" />'."\n";

	formEnd();
}
*/
?>
